import { createJsonFromDiscriminatorValue, serializeJson, type Json } from '../../../../../../../models/json';
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function createPriceMatPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoPriceMatPostRequestBody;
}
// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function deserializeIntoPriceMatPostRequestBody(priceMatPostRequestBody: PriceMatPostRequestBody | undefined = {} as PriceMatPostRequestBody) : Record<string, (node: ParseNode) => void> {
    return {
        "basis": n => { priceMatPostRequestBody.basis = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "issue": n => { priceMatPostRequestBody.issue = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "maturity": n => { priceMatPostRequestBody.maturity = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "rate": n => { priceMatPostRequestBody.rate = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "settlement": n => { priceMatPostRequestBody.settlement = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "yld": n => { priceMatPostRequestBody.yld = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
    }
}
export interface PriceMatPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The basis property
     */
    basis?: Json;
    /**
     * The issue property
     */
    issue?: Json;
    /**
     * The maturity property
     */
    maturity?: Json;
    /**
     * The rate property
     */
    rate?: Json;
    /**
     * The settlement property
     */
    settlement?: Json;
    /**
     * The yld property
     */
    yld?: Json;
}
// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function serializePriceMatPostRequestBody(writer: SerializationWriter, priceMatPostRequestBody: PriceMatPostRequestBody | undefined = {} as PriceMatPostRequestBody) : void {
        writer.writeObjectValue<Json>("basis", priceMatPostRequestBody.basis, );
        writer.writeObjectValue<Json>("issue", priceMatPostRequestBody.issue, );
        writer.writeObjectValue<Json>("maturity", priceMatPostRequestBody.maturity, );
        writer.writeObjectValue<Json>("rate", priceMatPostRequestBody.rate, );
        writer.writeObjectValue<Json>("settlement", priceMatPostRequestBody.settlement, );
        writer.writeObjectValue<Json>("yld", priceMatPostRequestBody.yld, );
        writer.writeAdditionalData(priceMatPostRequestBody.additionalData);
}
