export * from './createDegreesPostRequestBodyFromDiscriminatorValue'
export * from './degreesPostRequestBody'
export * from './degreesRequestBuilderPostRequestConfiguration'
export * from './deserializeIntoDegreesPostRequestBody'
export * from './serializeDegreesPostRequestBody'
