/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSharedWithChannelTeamInfoFromDiscriminatorValue, serializeSharedWithChannelTeamInfo, type SharedWithChannelTeamInfo } from '@microsoft/msgraph-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { AllowedMembersRequestBuilderNavigationMetadata, AllowedMembersRequestBuilderRequestsMetadata, type AllowedMembersRequestBuilder } from './allowedMembers/index.js';
// @ts-ignore
import { TeamRequestBuilderRequestsMetadata, type TeamRequestBuilder } from './team/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the sharedWithTeams property of the microsoft.graph.channel entity.
 */
export interface SharedWithChannelTeamInfoItemRequestBuilder extends BaseRequestBuilder<SharedWithChannelTeamInfoItemRequestBuilder> {
    /**
     * Provides operations to manage the allowedMembers property of the microsoft.graph.sharedWithChannelTeamInfo entity.
     */
    get allowedMembers(): AllowedMembersRequestBuilder;
    /**
     * Provides operations to manage the team property of the microsoft.graph.teamInfo entity.
     */
    get team(): TeamRequestBuilder;
    /**
     * Unshare a channel with a team by deleting the corresponding sharedWithChannelTeamInfo resource. This operation is allowed only for channels with a membershipType value of shared.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/sharedwithchannelteaminfo-delete?view=graph-rest-1.0|Find more info here}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get a team that has been shared with a specified channel. This operation is allowed only for channels with a membershipType value of shared.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharedWithChannelTeamInfo>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/sharedwithchannelteaminfo-get?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<SharedWithChannelTeamInfoItemRequestBuilderGetQueryParameters> | undefined) : Promise<SharedWithChannelTeamInfo | undefined>;
    /**
     * Update the navigation property sharedWithTeams in teams
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SharedWithChannelTeamInfo>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: SharedWithChannelTeamInfo, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SharedWithChannelTeamInfo | undefined>;
    /**
     * Unshare a channel with a team by deleting the corresponding sharedWithChannelTeamInfo resource. This operation is allowed only for channels with a membershipType value of shared.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get a team that has been shared with a specified channel. This operation is allowed only for channels with a membershipType value of shared.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SharedWithChannelTeamInfoItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property sharedWithTeams in teams
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: SharedWithChannelTeamInfo, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get a team that has been shared with a specified channel. This operation is allowed only for channels with a membershipType value of shared.
 */
export interface SharedWithChannelTeamInfoItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const SharedWithChannelTeamInfoItemRequestBuilderUriTemplate = "{+baseurl}/teams/{team%2Did}/channels/{channel%2Did}/sharedWithTeams/{sharedWithChannelTeamInfo%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SharedWithChannelTeamInfoItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SharedWithChannelTeamInfoItemRequestBuilderNavigationMetadata: Record<Exclude<keyof SharedWithChannelTeamInfoItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    allowedMembers: {
        requestsMetadata: AllowedMembersRequestBuilderRequestsMetadata,
        navigationMetadata: AllowedMembersRequestBuilderNavigationMetadata,
    },
    team: {
        requestsMetadata: TeamRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SharedWithChannelTeamInfoItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SharedWithChannelTeamInfoItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: SharedWithChannelTeamInfoItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharedWithChannelTeamInfoFromDiscriminatorValue,
        queryParametersMapper: SharedWithChannelTeamInfoItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: SharedWithChannelTeamInfoItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSharedWithChannelTeamInfoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSharedWithChannelTeamInfo,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
