export * from './createReplaceBPostRequestBodyFromDiscriminatorValue'
export * from './deserializeIntoReplaceBPostRequestBody'
export * from './replaceBPostRequestBody'
export * from './replaceBRequestBuilderPostRequestConfiguration'
export * from './serializeReplaceBPostRequestBody'
