/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCloudPcSourceDeviceImageFromDiscriminatorValue, deserializeIntoBaseCollectionPaginationCountResponse, serializeBaseCollectionPaginationCountResponse, serializeCloudPcSourceDeviceImage, type BaseCollectionPaginationCountResponse, type CloudPcSourceDeviceImage } from '@microsoft/msgraph-sdk/models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetSourceImagesGetResponse}
 */
export function createGetSourceImagesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetSourceImagesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoGetSourceImagesGetResponse(getSourceImagesGetResponse: Partial<GetSourceImagesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(getSourceImagesGetResponse),
        "value": n => { getSourceImagesGetResponse.value = n.getCollectionOfObjectValues<CloudPcSourceDeviceImage>(createCloudPcSourceDeviceImageFromDiscriminatorValue); },
    }
}
export interface GetSourceImagesGetResponse extends BaseCollectionPaginationCountResponse, Parsable {
    /**
     * The value property
     */
    value?: CloudPcSourceDeviceImage[];
}
/**
 * Provides operations to call the getSourceImages method.
 */
export interface GetSourceImagesRequestBuilder extends BaseRequestBuilder<GetSourceImagesRequestBuilder> {
    /**
     * Get cloudPcSourceDeviceImage objects that can be uploaded and used on Cloud PCs. View a list of all the managed image resources from your Microsoft Entra subscriptions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetSourceImagesGetResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<GetSourceImagesRequestBuilderGetQueryParameters> | undefined) : Promise<GetSourceImagesGetResponse | undefined>;
    /**
     * Get cloudPcSourceDeviceImage objects that can be uploaded and used on Cloud PCs. View a list of all the managed image resources from your Microsoft Entra subscriptions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GetSourceImagesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get cloudPcSourceDeviceImage objects that can be uploaded and used on Cloud PCs. View a list of all the managed image resources from your Microsoft Entra subscriptions.
 */
export interface GetSourceImagesRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeGetSourceImagesGetResponse(writer: SerializationWriter, getSourceImagesGetResponse: Partial<GetSourceImagesGetResponse> | undefined = {}) : void {
    serializeBaseCollectionPaginationCountResponse(writer, getSourceImagesGetResponse)
    writer.writeCollectionOfObjectValues<CloudPcSourceDeviceImage>("value", getSourceImagesGetResponse.value, serializeCloudPcSourceDeviceImage);
}
/**
 * Uri template for the request builder.
 */
export const GetSourceImagesRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/virtualEndpoint/deviceImages/getSourceImages(){?%24count,%24filter,%24search,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const GetSourceImagesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "filter": "%24filter",
    "search": "%24search",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const GetSourceImagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetSourceImagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createGetSourceImagesGetResponseFromDiscriminatorValue,
        queryParametersMapper: GetSourceImagesRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
