/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUserExperienceAnalyticsDevicePerformanceFromDiscriminatorValue, deserializeIntoBaseCollectionPaginationCountResponse, serializeBaseCollectionPaginationCountResponse, serializeUserExperienceAnalyticsDevicePerformance, type BaseCollectionPaginationCountResponse, type UserExperienceAnalyticsDevicePerformance } from '@microsoft/msgraph-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse}
 */
export function createSummarizeDevicePerformanceDevicesWithSummarizeByGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSummarizeDevicePerformanceDevicesWithSummarizeByGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoSummarizeDevicePerformanceDevicesWithSummarizeByGetResponse(summarizeDevicePerformanceDevicesWithSummarizeByGetResponse: Partial<SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(summarizeDevicePerformanceDevicesWithSummarizeByGetResponse),
        "value": n => { summarizeDevicePerformanceDevicesWithSummarizeByGetResponse.value = n.getCollectionOfObjectValues<UserExperienceAnalyticsDevicePerformance>(createUserExperienceAnalyticsDevicePerformanceFromDiscriminatorValue); },
    }
}
export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetOrderbyQueryParameterType = (typeof GetOrderbyQueryParameterTypeObject)[keyof typeof GetOrderbyQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeSummarizeDevicePerformanceDevicesWithSummarizeByGetResponse(writer: SerializationWriter, summarizeDevicePerformanceDevicesWithSummarizeByGetResponse: Partial<SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse> | undefined = {}) : void {
    serializeBaseCollectionPaginationCountResponse(writer, summarizeDevicePerformanceDevicesWithSummarizeByGetResponse)
    writer.writeCollectionOfObjectValues<UserExperienceAnalyticsDevicePerformance>("value", summarizeDevicePerformanceDevicesWithSummarizeByGetResponse.value, serializeUserExperienceAnalyticsDevicePerformance);
}
export interface SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse extends BaseCollectionPaginationCountResponse, Parsable {
    /**
     * The value property
     */
    value?: UserExperienceAnalyticsDevicePerformance[];
}
/**
 * Provides operations to call the summarizeDevicePerformanceDevices method.
 */
export interface SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilder extends BaseRequestBuilder<SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilder> {
    /**
     * Invoke function summarizeDevicePerformanceDevices
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderGetQueryParameters> | undefined) : Promise<SummarizeDevicePerformanceDevicesWithSummarizeByGetResponse | undefined>;
    /**
     * Invoke function summarizeDevicePerformanceDevices
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Invoke function summarizeDevicePerformanceDevices
 */
export interface SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: GetOrderbyQueryParameterType[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderUriTemplate = "{+baseurl}/deviceManagement/userExperienceAnalyticsDevicePerformance/summarizeDevicePerformanceDevices(summarizeBy='{summarizeBy}'){?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Provides operations to call the summarizeDevicePerformanceDevices method.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
} as const;
/**
 * Provides operations to call the summarizeDevicePerformanceDevices method.
 */
export const GetOrderbyQueryParameterTypeObject = {
    Id: "id",
    IdDesc: "id desc",
    AverageBlueScreens: "averageBlueScreens",
    AverageBlueScreensDesc: "averageBlueScreens desc",
    AverageRestarts: "averageRestarts",
    AverageRestartsDesc: "averageRestarts desc",
    BlueScreenCount: "blueScreenCount",
    BlueScreenCountDesc: "blueScreenCount desc",
    BootScore: "bootScore",
    BootScoreDesc: "bootScore desc",
    CoreBootTimeInMs: "coreBootTimeInMs",
    CoreBootTimeInMsDesc: "coreBootTimeInMs desc",
    CoreLoginTimeInMs: "coreLoginTimeInMs",
    CoreLoginTimeInMsDesc: "coreLoginTimeInMs desc",
    DeviceCount: "deviceCount",
    DeviceCountDesc: "deviceCount desc",
    DeviceName: "deviceName",
    DeviceNameDesc: "deviceName desc",
    DiskType: "diskType",
    DiskTypeDesc: "diskType desc",
    GroupPolicyBootTimeInMs: "groupPolicyBootTimeInMs",
    GroupPolicyBootTimeInMsDesc: "groupPolicyBootTimeInMs desc",
    GroupPolicyLoginTimeInMs: "groupPolicyLoginTimeInMs",
    GroupPolicyLoginTimeInMsDesc: "groupPolicyLoginTimeInMs desc",
    HealthStatus: "healthStatus",
    HealthStatusDesc: "healthStatus desc",
    LoginScore: "loginScore",
    LoginScoreDesc: "loginScore desc",
    Manufacturer: "manufacturer",
    ManufacturerDesc: "manufacturer desc",
    Model: "model",
    ModelDesc: "model desc",
    ModelStartupPerformanceScore: "modelStartupPerformanceScore",
    ModelStartupPerformanceScoreDesc: "modelStartupPerformanceScore desc",
    OperatingSystemVersion: "operatingSystemVersion",
    OperatingSystemVersionDesc: "operatingSystemVersion desc",
    ResponsiveDesktopTimeInMs: "responsiveDesktopTimeInMs",
    ResponsiveDesktopTimeInMsDesc: "responsiveDesktopTimeInMs desc",
    RestartCount: "restartCount",
    RestartCountDesc: "restartCount desc",
    StartupPerformanceScore: "startupPerformanceScore",
    StartupPerformanceScoreDesc: "startupPerformanceScore desc",
} as const;
/**
 * Provides operations to call the summarizeDevicePerformanceDevices method.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    AverageBlueScreens: "averageBlueScreens",
    AverageRestarts: "averageRestarts",
    BlueScreenCount: "blueScreenCount",
    BootScore: "bootScore",
    CoreBootTimeInMs: "coreBootTimeInMs",
    CoreLoginTimeInMs: "coreLoginTimeInMs",
    DeviceCount: "deviceCount",
    DeviceName: "deviceName",
    DiskType: "diskType",
    GroupPolicyBootTimeInMs: "groupPolicyBootTimeInMs",
    GroupPolicyLoginTimeInMs: "groupPolicyLoginTimeInMs",
    HealthStatus: "healthStatus",
    LoginScore: "loginScore",
    Manufacturer: "manufacturer",
    Model: "model",
    ModelStartupPerformanceScore: "modelStartupPerformanceScore",
    OperatingSystemVersion: "operatingSystemVersion",
    ResponsiveDesktopTimeInMs: "responsiveDesktopTimeInMs",
    RestartCount: "restartCount",
    StartupPerformanceScore: "startupPerformanceScore",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSummarizeDevicePerformanceDevicesWithSummarizeByGetResponseFromDiscriminatorValue,
        queryParametersMapper: SummarizeDevicePerformanceDevicesWithSummarizeByRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
