// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createDriveRecipientFromDiscriminatorValue, serializeDriveRecipient, type DriveRecipient } from '../../../../models/driveRecipient';
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createGrantPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoGrantPostRequestBody;
}
export function deserializeIntoGrantPostRequestBody(grantPostRequestBody: GrantPostRequestBody | undefined = {} as GrantPostRequestBody) : Record<string, (node: ParseNode) => void> {
    return {
        "recipients": n => { grantPostRequestBody.recipients = n.getCollectionOfObjectValues<DriveRecipient>(createDriveRecipientFromDiscriminatorValue); },
        "roles": n => { grantPostRequestBody.roles = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
export interface GrantPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The recipients property
     */
    recipients?: DriveRecipient[];
    /**
     * The roles property
     */
    roles?: string[];
}
export function serializeGrantPostRequestBody(writer: SerializationWriter, grantPostRequestBody: GrantPostRequestBody | undefined = {} as GrantPostRequestBody) : void {
        writer.writeCollectionOfObjectValues<DriveRecipient>("recipients", grantPostRequestBody.recipients, serializeDriveRecipient);
        writer.writeCollectionOfPrimitiveValues<string>("roles", grantPostRequestBody.roles);
        writer.writeAdditionalData(grantPostRequestBody.additionalData);
}
// tslint:enable
// eslint-enable
