export * from './userExperienceAnalyticsDeviceStartupHistoryItemRequestBuilderDeleteRequestConfiguration'
export * from './userExperienceAnalyticsDeviceStartupHistoryItemRequestBuilderGetQueryParameters'
export * from './userExperienceAnalyticsDeviceStartupHistoryItemRequestBuilderGetRequestConfiguration'
export * from './userExperienceAnalyticsDeviceStartupHistoryItemRequestBuilderPatchRequestConfiguration'
