/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createOrganizationalBrandingFromDiscriminatorValue, serializeOrganizationalBranding, type OrganizationalBranding } from '../../../models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../../models/oDataErrors/';
import { BackgroundImageRequestBuilderRequestsMetadata, BackgroundImageRequestBuilderUriTemplate, type BackgroundImageRequestBuilder } from './backgroundImage/';
import { BannerLogoRequestBuilderRequestsMetadata, BannerLogoRequestBuilderUriTemplate, type BannerLogoRequestBuilder } from './bannerLogo/';
import { CustomCSSRequestBuilderRequestsMetadata, CustomCSSRequestBuilderUriTemplate, type CustomCSSRequestBuilder } from './customCSS/';
import { FaviconRequestBuilderRequestsMetadata, FaviconRequestBuilderUriTemplate, type FaviconRequestBuilder } from './favicon/';
import { HeaderLogoRequestBuilderRequestsMetadata, HeaderLogoRequestBuilderUriTemplate, type HeaderLogoRequestBuilder } from './headerLogo/';
import { LocalizationsRequestBuilderNavigationMetadata, LocalizationsRequestBuilderRequestsMetadata, LocalizationsRequestBuilderUriTemplate, type LocalizationsRequestBuilder } from './localizations/';
import { SquareLogoRequestBuilderRequestsMetadata, SquareLogoRequestBuilderUriTemplate, type SquareLogoRequestBuilder } from './squareLogo/';
import { SquareLogoDarkRequestBuilderRequestsMetadata, SquareLogoDarkRequestBuilderUriTemplate, type SquareLogoDarkRequestBuilder } from './squareLogoDark/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the branding property of the microsoft.graph.organization entity.
 */
export interface BrandingRequestBuilder extends BaseRequestBuilder<BrandingRequestBuilder> {
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get backgroundImage(): BackgroundImageRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get bannerLogo(): BannerLogoRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get customCSS(): CustomCSSRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get favicon(): FaviconRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get headerLogo(): HeaderLogoRequestBuilder;
    /**
     * Provides operations to manage the localizations property of the microsoft.graph.organizationalBranding entity.
     */
    get localizations(): LocalizationsRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get squareLogo(): SquareLogoRequestBuilder;
    /**
     * Provides operations to manage the media for the organization entity.
     */
    get squareLogoDark(): SquareLogoDarkRequestBuilder;
    /**
     * Delete the default organizational branding object. To delete the organizationalBranding object, all images (Stream types) must first be removed from the object.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @see {@link https://learn.microsoft.com/graph/api/organizationalbranding-delete?view=graph-rest-1.0|Find more info here}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Retrieve the default organizational branding object, if the Accept-Language header is set to 0 or default. If no default organizational branding object exists, this method returns a 404 Not Found error. If the Accept-Language header is set to an existing locale identified by the value of its id, this method retrieves the branding for the specified locale. This method retrieves only non-Stream properties, for example, usernameHintText and signInPageText. To retrieve Stream types of the default branding, for example, bannerLogo and backgroundImage, use the GET organizationalBrandingLocalization method.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of OrganizationalBranding
     * @see {@link https://learn.microsoft.com/graph/api/organizationalbranding-get?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<BrandingRequestBuilderGetQueryParameters> | undefined) : Promise<OrganizationalBranding | undefined>;
    /**
     * Update the properties of the default branding object specified by the organizationalBranding resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of OrganizationalBranding
     * @see {@link https://learn.microsoft.com/graph/api/organizationalbranding-update?view=graph-rest-1.0|Find more info here}
     */
     patch(body: OrganizationalBranding, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationalBranding | undefined>;
    /**
     * Delete the default organizational branding object. To delete the organizationalBranding object, all images (Stream types) must first be removed from the object.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Retrieve the default organizational branding object, if the Accept-Language header is set to 0 or default. If no default organizational branding object exists, this method returns a 404 Not Found error. If the Accept-Language header is set to an existing locale identified by the value of its id, this method retrieves the branding for the specified locale. This method retrieves only non-Stream properties, for example, usernameHintText and signInPageText. To retrieve Stream types of the default branding, for example, bannerLogo and backgroundImage, use the GET organizationalBrandingLocalization method.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<BrandingRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the properties of the default branding object specified by the organizationalBranding resource.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPatchRequestInformation(body: OrganizationalBranding, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Retrieve the default organizational branding object, if the Accept-Language header is set to 0 or default. If no default organizational branding object exists, this method returns a 404 Not Found error. If the Accept-Language header is set to an existing locale identified by the value of its id, this method retrieves the branding for the specified locale. This method retrieves only non-Stream properties, for example, usernameHintText and signInPageText. To retrieve Stream types of the default branding, for example, bannerLogo and backgroundImage, use the GET organizationalBrandingLocalization method.
 */
export interface BrandingRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const BrandingRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BrandingRequestBuilderNavigationMetadata: Record<Exclude<keyof BrandingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    backgroundImage: {
        uriTemplate: BackgroundImageRequestBuilderUriTemplate,
        requestsMetadata: BackgroundImageRequestBuilderRequestsMetadata,
    },
    bannerLogo: {
        uriTemplate: BannerLogoRequestBuilderUriTemplate,
        requestsMetadata: BannerLogoRequestBuilderRequestsMetadata,
    },
    customCSS: {
        uriTemplate: CustomCSSRequestBuilderUriTemplate,
        requestsMetadata: CustomCSSRequestBuilderRequestsMetadata,
    },
    favicon: {
        uriTemplate: FaviconRequestBuilderUriTemplate,
        requestsMetadata: FaviconRequestBuilderRequestsMetadata,
    },
    headerLogo: {
        uriTemplate: HeaderLogoRequestBuilderUriTemplate,
        requestsMetadata: HeaderLogoRequestBuilderRequestsMetadata,
    },
    localizations: {
        uriTemplate: LocalizationsRequestBuilderUriTemplate,
        requestsMetadata: LocalizationsRequestBuilderRequestsMetadata,
        navigationMetadata: LocalizationsRequestBuilderNavigationMetadata,
    },
    squareLogo: {
        uriTemplate: SquareLogoRequestBuilderUriTemplate,
        requestsMetadata: SquareLogoRequestBuilderRequestsMetadata,
    },
    squareLogoDark: {
        uriTemplate: SquareLogoDarkRequestBuilderUriTemplate,
        requestsMetadata: SquareLogoDarkRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BrandingRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContentAsync",
    },
    get: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createOrganizationalBrandingFromDiscriminatorValue,
        queryParametersMapper: BrandingRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        responseBodyContentType: "application/json",
        errorMappings: {
            _4XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            _5XX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createOrganizationalBrandingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOrganizationalBranding,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const BrandingRequestBuilderUriTemplate = "{+baseurl}/organization/{organization%2Did}/branding{?%24select,%24expand}";
/* tslint:enable */
/* eslint-enable */
