/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createCallFromDiscriminatorValue, serializeCall, type Call } from '@microsoft/msgraph-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/';
import { AddLargeGalleryViewRequestBuilderRequestsMetadata, type AddLargeGalleryViewRequestBuilder } from './addLargeGalleryView/';
import { AnswerRequestBuilderRequestsMetadata, type AnswerRequestBuilder } from './answer/';
import { AudioRoutingGroupsRequestBuilderNavigationMetadata, AudioRoutingGroupsRequestBuilderRequestsMetadata, type AudioRoutingGroupsRequestBuilder } from './audioRoutingGroups/';
import { CancelMediaProcessingRequestBuilderRequestsMetadata, type CancelMediaProcessingRequestBuilder } from './cancelMediaProcessing/';
import { ChangeScreenSharingRoleRequestBuilderRequestsMetadata, type ChangeScreenSharingRoleRequestBuilder } from './changeScreenSharingRole/';
import { ContentSharingSessionsRequestBuilderNavigationMetadata, ContentSharingSessionsRequestBuilderRequestsMetadata, type ContentSharingSessionsRequestBuilder } from './contentSharingSessions/';
import { KeepAliveRequestBuilderRequestsMetadata, type KeepAliveRequestBuilder } from './keepAlive/';
import { MuteRequestBuilderRequestsMetadata, type MuteRequestBuilder } from './mute/';
import { OperationsRequestBuilderNavigationMetadata, OperationsRequestBuilderRequestsMetadata, type OperationsRequestBuilder } from './operations/';
import { ParticipantsRequestBuilderNavigationMetadata, ParticipantsRequestBuilderRequestsMetadata, type ParticipantsRequestBuilder } from './participants/';
import { PlayPromptRequestBuilderRequestsMetadata, type PlayPromptRequestBuilder } from './playPrompt/';
import { RecordResponseRequestBuilderRequestsMetadata, type RecordResponseRequestBuilder } from './recordResponse/';
import { RedirectRequestBuilderRequestsMetadata, type RedirectRequestBuilder } from './redirect/';
import { RejectRequestBuilderRequestsMetadata, type RejectRequestBuilder } from './reject/';
import { SendDtmfTonesRequestBuilderRequestsMetadata, type SendDtmfTonesRequestBuilder } from './sendDtmfTones/';
import { SubscribeToToneRequestBuilderRequestsMetadata, type SubscribeToToneRequestBuilder } from './subscribeToTone/';
import { TransferRequestBuilderRequestsMetadata, type TransferRequestBuilder } from './transfer/';
import { type UnmuteRequestBuilder, UnmuteRequestBuilderRequestsMetadata } from './unmute/';
import { type UpdateRecordingStatusRequestBuilder, UpdateRecordingStatusRequestBuilderRequestsMetadata } from './updateRecordingStatus/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the calls property of the microsoft.graph.cloudCommunications entity.
 */
export interface CallItemRequestBuilder extends BaseRequestBuilder<CallItemRequestBuilder> {
    /**
     * Provides operations to call the addLargeGalleryView method.
     */
    get addLargeGalleryView(): AddLargeGalleryViewRequestBuilder;
    /**
     * Provides operations to call the answer method.
     */
    get answer(): AnswerRequestBuilder;
    /**
     * Provides operations to manage the audioRoutingGroups property of the microsoft.graph.call entity.
     */
    get audioRoutingGroups(): AudioRoutingGroupsRequestBuilder;
    /**
     * Provides operations to call the cancelMediaProcessing method.
     */
    get cancelMediaProcessing(): CancelMediaProcessingRequestBuilder;
    /**
     * Provides operations to call the changeScreenSharingRole method.
     */
    get changeScreenSharingRole(): ChangeScreenSharingRoleRequestBuilder;
    /**
     * Provides operations to manage the contentSharingSessions property of the microsoft.graph.call entity.
     */
    get contentSharingSessions(): ContentSharingSessionsRequestBuilder;
    /**
     * Provides operations to call the keepAlive method.
     */
    get keepAlive(): KeepAliveRequestBuilder;
    /**
     * Provides operations to call the mute method.
     */
    get mute(): MuteRequestBuilder;
    /**
     * Provides operations to manage the operations property of the microsoft.graph.call entity.
     */
    get operations(): OperationsRequestBuilder;
    /**
     * Provides operations to manage the participants property of the microsoft.graph.call entity.
     */
    get participants(): ParticipantsRequestBuilder;
    /**
     * Provides operations to call the playPrompt method.
     */
    get playPrompt(): PlayPromptRequestBuilder;
    /**
     * Provides operations to call the recordResponse method.
     */
    get recordResponse(): RecordResponseRequestBuilder;
    /**
     * Provides operations to call the redirect method.
     */
    get redirect(): RedirectRequestBuilder;
    /**
     * Provides operations to call the reject method.
     */
    get reject(): RejectRequestBuilder;
    /**
     * Provides operations to call the sendDtmfTones method.
     */
    get sendDtmfTones(): SendDtmfTonesRequestBuilder;
    /**
     * Provides operations to call the subscribeToTone method.
     */
    get subscribeToTone(): SubscribeToToneRequestBuilder;
    /**
     * Provides operations to call the transfer method.
     */
    get transfer(): TransferRequestBuilder;
    /**
     * Provides operations to call the unmute method.
     */
    get unmute(): UnmuteRequestBuilder;
    /**
     * Provides operations to call the updateRecordingStatus method.
     */
    get updateRecordingStatus(): UpdateRecordingStatusRequestBuilder;
    /**
     * Delete or hang up an active call. For group calls, this will only delete your call leg and the underlying group call will still continue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/call-delete?view=graph-rest-1.0|Find more info here}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Retrieve the properties and relationships of a call object.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Call>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/call-get?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<CallItemRequestBuilderGetQueryParameters> | undefined) : Promise<Call | undefined>;
    /**
     * Update the navigation property calls in communications
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Call>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: Call, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Call | undefined>;
    /**
     * Delete or hang up an active call. For group calls, this will only delete your call leg and the underlying group call will still continue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Retrieve the properties and relationships of a call object.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CallItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property calls in communications
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: Call, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Retrieve the properties and relationships of a call object.
 */
export interface CallItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
}
export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const CallItemRequestBuilderUriTemplate = "{+baseurl}/communications/calls/{call%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CallItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CallItemRequestBuilderNavigationMetadata: Record<Exclude<keyof CallItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    addLargeGalleryView: {
        requestsMetadata: AddLargeGalleryViewRequestBuilderRequestsMetadata,
    },
    answer: {
        requestsMetadata: AnswerRequestBuilderRequestsMetadata,
    },
    audioRoutingGroups: {
        requestsMetadata: AudioRoutingGroupsRequestBuilderRequestsMetadata,
        navigationMetadata: AudioRoutingGroupsRequestBuilderNavigationMetadata,
    },
    cancelMediaProcessing: {
        requestsMetadata: CancelMediaProcessingRequestBuilderRequestsMetadata,
    },
    changeScreenSharingRole: {
        requestsMetadata: ChangeScreenSharingRoleRequestBuilderRequestsMetadata,
    },
    contentSharingSessions: {
        requestsMetadata: ContentSharingSessionsRequestBuilderRequestsMetadata,
        navigationMetadata: ContentSharingSessionsRequestBuilderNavigationMetadata,
    },
    keepAlive: {
        requestsMetadata: KeepAliveRequestBuilderRequestsMetadata,
    },
    mute: {
        requestsMetadata: MuteRequestBuilderRequestsMetadata,
    },
    operations: {
        requestsMetadata: OperationsRequestBuilderRequestsMetadata,
        navigationMetadata: OperationsRequestBuilderNavigationMetadata,
    },
    participants: {
        requestsMetadata: ParticipantsRequestBuilderRequestsMetadata,
        navigationMetadata: ParticipantsRequestBuilderNavigationMetadata,
    },
    playPrompt: {
        requestsMetadata: PlayPromptRequestBuilderRequestsMetadata,
    },
    recordResponse: {
        requestsMetadata: RecordResponseRequestBuilderRequestsMetadata,
    },
    redirect: {
        requestsMetadata: RedirectRequestBuilderRequestsMetadata,
    },
    reject: {
        requestsMetadata: RejectRequestBuilderRequestsMetadata,
    },
    sendDtmfTones: {
        requestsMetadata: SendDtmfTonesRequestBuilderRequestsMetadata,
    },
    subscribeToTone: {
        requestsMetadata: SubscribeToToneRequestBuilderRequestsMetadata,
    },
    transfer: {
        requestsMetadata: TransferRequestBuilderRequestsMetadata,
    },
    unmute: {
        requestsMetadata: UnmuteRequestBuilderRequestsMetadata,
    },
    updateRecordingStatus: {
        requestsMetadata: UpdateRecordingStatusRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CallItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: CallItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: CallItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCallFromDiscriminatorValue,
        queryParametersMapper: CallItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: CallItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCallFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCall,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Provides operations to manage the calls property of the microsoft.graph.cloudCommunications entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
    AudioRoutingGroups: "audioRoutingGroups",
    ContentSharingSessions: "contentSharingSessions",
    Operations: "operations",
    Participants: "participants",
} as const;
/**
 * Provides operations to manage the calls property of the microsoft.graph.cloudCommunications entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    CallbackUri: "callbackUri",
    CallChainId: "callChainId",
    CallOptions: "callOptions",
    CallRoutes: "callRoutes",
    ChatInfo: "chatInfo",
    Direction: "direction",
    IncomingContext: "incomingContext",
    MediaConfig: "mediaConfig",
    MediaState: "mediaState",
    MeetingInfo: "meetingInfo",
    MyParticipantId: "myParticipantId",
    RequestedModalities: "requestedModalities",
    ResultInfo: "resultInfo",
    Source: "source",
    State: "state",
    Subject: "subject",
    Targets: "targets",
    TenantId: "tenantId",
    ToneInfo: "toneInfo",
    Transcription: "transcription",
    AudioRoutingGroups: "audioRoutingGroups",
    ContentSharingSessions: "contentSharingSessions",
    Operations: "operations",
    Participants: "participants",
} as const;
/* tslint:enable */
/* eslint-enable */
