export * from './userExperienceAnalyticsAppHealthOSVersionPerformanceItemRequestBuilderDeleteRequestConfiguration'
export * from './userExperienceAnalyticsAppHealthOSVersionPerformanceItemRequestBuilderGetQueryParameters'
export * from './userExperienceAnalyticsAppHealthOSVersionPerformanceItemRequestBuilderGetRequestConfiguration'
export * from './userExperienceAnalyticsAppHealthOSVersionPerformanceItemRequestBuilderPatchRequestConfiguration'
