/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecoveryFromDiscriminatorValue, serializeRecovery, type Recovery } from '@microsoft/msgraph-sdk/models/entraRecoveryServices/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/index.js';
// @ts-ignore
import { JobsRequestBuilderNavigationMetadata, JobsRequestBuilderRequestsMetadata, type JobsRequestBuilder } from './jobs/index.js';
// @ts-ignore
import { SnapshotsRequestBuilderNavigationMetadata, SnapshotsRequestBuilderRequestsMetadata, type SnapshotsRequestBuilder } from './snapshots/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the recovery property of the microsoft.graph.directory entity.
 */
export interface RecoveryRequestBuilder extends BaseRequestBuilder<RecoveryRequestBuilder> {
    /**
     * Provides operations to manage the jobs property of the microsoft.graph.entraRecoveryServices.recovery entity.
     */
    get jobs(): JobsRequestBuilder;
    /**
     * Provides operations to manage the snapshots property of the microsoft.graph.entraRecoveryServices.recovery entity.
     */
    get snapshots(): SnapshotsRequestBuilder;
    /**
     * Delete navigation property recovery for directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get recovery from directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Recovery>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<RecoveryRequestBuilderGetQueryParameters> | undefined) : Promise<Recovery | undefined>;
    /**
     * Update the navigation property recovery in directory
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Recovery>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: Recovery, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Recovery | undefined>;
    /**
     * Delete navigation property recovery for directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get recovery from directory
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RecoveryRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property recovery in directory
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: Recovery, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get recovery from directory
 */
export interface RecoveryRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const RecoveryRequestBuilderUriTemplate = "{+baseurl}/directory/recovery{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RecoveryRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecoveryRequestBuilderNavigationMetadata: Record<Exclude<keyof RecoveryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    jobs: {
        requestsMetadata: JobsRequestBuilderRequestsMetadata,
        navigationMetadata: JobsRequestBuilderNavigationMetadata,
    },
    snapshots: {
        requestsMetadata: SnapshotsRequestBuilderRequestsMetadata,
        navigationMetadata: SnapshotsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecoveryRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RecoveryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: RecoveryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRecoveryFromDiscriminatorValue,
        queryParametersMapper: RecoveryRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: RecoveryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRecoveryFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecovery,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
