/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createPartnersFromDiscriminatorValue, serializePartners, type Partners } from '@microsoft/msgraph-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/';
import { BillingRequestBuilderNavigationMetadata, BillingRequestBuilderRequestsMetadata, type BillingRequestBuilder } from './billing/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetExpandQueryParameterType = (typeof GetExpandQueryParameterTypeObject)[keyof typeof GetExpandQueryParameterTypeObject];
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Provides operations to manage the partners property of the microsoft.graph.reportRoot entity.
 */
export interface PartnersRequestBuilder extends BaseRequestBuilder<PartnersRequestBuilder> {
    /**
     * Provides operations to manage the billing property of the microsoft.graph.partners entity.
     */
    get billing(): BillingRequestBuilder;
    /**
     * Delete navigation property partners for reports
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Represents billing details for a Microsoft direct partner.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Partners>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<PartnersRequestBuilderGetQueryParameters> | undefined) : Promise<Partners | undefined>;
    /**
     * Update the navigation property partners in reports
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Partners>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: Partners, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Partners | undefined>;
    /**
     * Delete navigation property partners for reports
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Represents billing details for a Microsoft direct partner.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PartnersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property partners in reports
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: Partners, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Represents billing details for a Microsoft direct partner.
 */
export interface PartnersRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: GetExpandQueryParameterType[];
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
}
/**
 * Uri template for the request builder.
 */
export const PartnersRequestBuilderUriTemplate = "{+baseurl}/reports/partners{?%24expand,%24select}";
/**
 * Provides operations to manage the partners property of the microsoft.graph.reportRoot entity.
 */
export const GetExpandQueryParameterTypeObject = {
    Asterisk: "*",
    Billing: "billing",
} as const;
/**
 * Provides operations to manage the partners property of the microsoft.graph.reportRoot entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    Billing: "billing",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const PartnersRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PartnersRequestBuilderNavigationMetadata: Record<Exclude<keyof PartnersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    billing: {
        requestsMetadata: BillingRequestBuilderRequestsMetadata,
        navigationMetadata: BillingRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PartnersRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: PartnersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: PartnersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPartnersFromDiscriminatorValue,
        queryParametersMapper: PartnersRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: PartnersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPartnersFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePartners,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
