// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoBaseCollectionPaginationCountResponse, serializeBaseCollectionPaginationCountResponse, type BaseCollectionPaginationCountResponse } from '../../models/baseCollectionPaginationCountResponse';
import { createConvertIdResultFromDiscriminatorValue, serializeConvertIdResult, type ConvertIdResult } from '../../models/convertIdResult';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createTranslateExchangeIdsPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoTranslateExchangeIdsPostResponse;
}
export function deserializeIntoTranslateExchangeIdsPostResponse(translateExchangeIdsPostResponse: TranslateExchangeIdsPostResponse | undefined = {} as TranslateExchangeIdsPostResponse) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(translateExchangeIdsPostResponse),
        "value": n => { translateExchangeIdsPostResponse.value = n.getCollectionOfObjectValues<ConvertIdResult>(createConvertIdResultFromDiscriminatorValue); },
    }
}
export function serializeTranslateExchangeIdsPostResponse(writer: SerializationWriter, translateExchangeIdsPostResponse: TranslateExchangeIdsPostResponse | undefined = {} as TranslateExchangeIdsPostResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, translateExchangeIdsPostResponse)
        writer.writeCollectionOfObjectValues<ConvertIdResult>("value", translateExchangeIdsPostResponse.value, );
}
export interface TranslateExchangeIdsPostResponse extends BaseCollectionPaginationCountResponse, Parsable {
    /**
     * The value property
     */
    value?: ConvertIdResult[];
}
// tslint:enable
// eslint-enable
