export * from './createCreateNewVersionPostRequestBodyFromDiscriminatorValue'
export * from './createNewVersionPostRequestBody'
export * from './deserializeIntoCreateNewVersionPostRequestBody'
export * from './microsoftGraphIdentityGovernanceCreateNewVersionRequestBuilderPostRequestConfiguration'
export * from './serializeCreateNewVersionPostRequestBody'
