export * from './createGetVirtualAppointmentJoinWebUrlResponseFromDiscriminatorValue'
export * from './deserializeIntoGetVirtualAppointmentJoinWebUrlResponse'
export * from './getVirtualAppointmentJoinWebUrlRequestBuilderGetRequestConfiguration'
export * from './getVirtualAppointmentJoinWebUrlResponse'
export * from './serializeGetVirtualAppointmentJoinWebUrlResponse'
