/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createConversationFromDiscriminatorValue, type Conversation } from '@microsoft/msgraph-sdk/models/';
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/';
import { ThreadsRequestBuilderNavigationMetadata, ThreadsRequestBuilderRequestsMetadata, type ThreadsRequestBuilder } from './threads/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the conversations property of the microsoft.graph.group entity.
 */
export interface ConversationItemRequestBuilder extends BaseRequestBuilder<ConversationItemRequestBuilder> {
    /**
     * Provides operations to manage the threads property of the microsoft.graph.conversation entity.
     */
    get threads(): ThreadsRequestBuilder;
    /**
     * Delete conversation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/group-delete-conversation?view=graph-rest-1.0|Find more info here}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * The group's conversations.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Conversation>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @see {@link https://learn.microsoft.com/graph/api/group-get-conversation?view=graph-rest-1.0|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<ConversationItemRequestBuilderGetQueryParameters> | undefined) : Promise<Conversation | undefined>;
    /**
     * Delete conversation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * The group's conversations.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ConversationItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * The group's conversations.
 */
export interface ConversationItemRequestBuilderGetQueryParameters {
    /**
     * Select properties to be returned
     */
    select?: GetSelectQueryParameterType[];
}
export type GetSelectQueryParameterType = (typeof GetSelectQueryParameterTypeObject)[keyof typeof GetSelectQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const ConversationItemRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}/conversations/{conversation%2Did}{?%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ConversationItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    threads: {
        requestsMetadata: ThreadsRequestBuilderRequestsMetadata,
        navigationMetadata: ThreadsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ConversationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ConversationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: ConversationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createConversationFromDiscriminatorValue,
        queryParametersMapper: ConversationItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Provides operations to manage the conversations property of the microsoft.graph.group entity.
 */
export const GetSelectQueryParameterTypeObject = {
    Id: "id",
    HasAttachments: "hasAttachments",
    LastDeliveredDateTime: "lastDeliveredDateTime",
    Preview: "preview",
    Topic: "topic",
    UniqueSenders: "uniqueSenders",
    Threads: "threads",
} as const;
/* tslint:enable */
/* eslint-enable */
