/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RefRequestBuilderRequestsMetadata, type RefRequestBuilder } from './ref/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /servicePrincipals/{servicePrincipal-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}
 */
export interface HomeRealmDiscoveryPolicyItemRequestBuilder extends BaseRequestBuilder<HomeRealmDiscoveryPolicyItemRequestBuilder> {
    /**
     * Provides operations to manage the collection of servicePrincipal entities.
     */
    get ref(): RefRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HomeRealmDiscoveryPolicyItemRequestBuilderUriTemplate = "{+baseurl}/servicePrincipals/{servicePrincipal%2Did}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HomeRealmDiscoveryPolicyItemRequestBuilderNavigationMetadata: Record<Exclude<keyof HomeRealmDiscoveryPolicyItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    ref: {
        requestsMetadata: RefRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
