// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createJsonFromDiscriminatorValue, serializeJson, type Json } from '../../../../../../../models/json';
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createPpmtPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoPpmtPostRequestBody;
}
export function deserializeIntoPpmtPostRequestBody(ppmtPostRequestBody: PpmtPostRequestBody | undefined = {} as PpmtPostRequestBody) : Record<string, (node: ParseNode) => void> {
    return {
        "fv": n => { ppmtPostRequestBody.fv = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "nper": n => { ppmtPostRequestBody.nper = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "per": n => { ppmtPostRequestBody.per = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "pv": n => { ppmtPostRequestBody.pv = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "rate": n => { ppmtPostRequestBody.rate = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
        "type": n => { ppmtPostRequestBody.type = n.getObjectValue<Json>(createJsonFromDiscriminatorValue); },
    }
}
export interface PpmtPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The fv property
     */
    fv?: Json;
    /**
     * The nper property
     */
    nper?: Json;
    /**
     * The per property
     */
    per?: Json;
    /**
     * The pv property
     */
    pv?: Json;
    /**
     * The rate property
     */
    rate?: Json;
    /**
     * The type property
     */
    type?: Json;
}
export function serializePpmtPostRequestBody(writer: SerializationWriter, ppmtPostRequestBody: PpmtPostRequestBody | undefined = {} as PpmtPostRequestBody) : void {
    writer.writeObjectValue<Json>("fv", ppmtPostRequestBody.fv, serializeJson);
    writer.writeObjectValue<Json>("nper", ppmtPostRequestBody.nper, serializeJson);
    writer.writeObjectValue<Json>("per", ppmtPostRequestBody.per, serializeJson);
    writer.writeObjectValue<Json>("pv", ppmtPostRequestBody.pv, serializeJson);
    writer.writeObjectValue<Json>("rate", ppmtPostRequestBody.rate, serializeJson);
    writer.writeObjectValue<Json>("type", ppmtPostRequestBody.type, serializeJson);
    writer.writeAdditionalData(ppmtPostRequestBody.additionalData);
}
// tslint:enable
// eslint-enable
