export * from './userExperienceAnalyticsDeviceStartupProcessPerformanceItemRequestBuilderDeleteRequestConfiguration'
export * from './userExperienceAnalyticsDeviceStartupProcessPerformanceItemRequestBuilderGetQueryParameters'
export * from './userExperienceAnalyticsDeviceStartupProcessPerformanceItemRequestBuilderGetRequestConfiguration'
export * from './userExperienceAnalyticsDeviceStartupProcessPerformanceItemRequestBuilderPatchRequestConfiguration'
