export * from './userExperienceAnalyticsMetricHistoryItemRequestBuilderDeleteRequestConfiguration'
export * from './userExperienceAnalyticsMetricHistoryItemRequestBuilderGetQueryParameters'
export * from './userExperienceAnalyticsMetricHistoryItemRequestBuilderGetRequestConfiguration'
export * from './userExperienceAnalyticsMetricHistoryItemRequestBuilderPatchRequestConfiguration'
