/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdministrativeUnitFromDiscriminatorValue, serializeAdministrativeUnit, type AdministrativeUnit } from '@microsoft/msgraph-sdk/models/';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '@microsoft/msgraph-sdk/models/oDataErrors/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the administrativeUnit property of the microsoft.graph.educationSchool entity.
 */
export interface AdministrativeUnitRequestBuilder extends BaseRequestBuilder<AdministrativeUnitRequestBuilder> {
    /**
     * The underlying administrativeUnit for this school.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdministrativeUnit>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<AdministrativeUnitRequestBuilderGetQueryParameters> | undefined) : Promise<AdministrativeUnit | undefined>;
    /**
     * Update the navigation property administrativeUnit in education
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdministrativeUnit>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: AdministrativeUnit, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdministrativeUnit | undefined>;
    /**
     * The underlying administrativeUnit for this school.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AdministrativeUnitRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property administrativeUnit in education
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: AdministrativeUnit, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The underlying administrativeUnit for this school.
 */
export interface AdministrativeUnitRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const AdministrativeUnitRequestBuilderUriTemplate = "{+baseurl}/education/schools/{educationSchool%2Did}/administrativeUnit{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AdministrativeUnitRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AdministrativeUnitRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AdministrativeUnitRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdministrativeUnitFromDiscriminatorValue,
        queryParametersMapper: AdministrativeUnitRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: AdministrativeUnitRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdministrativeUnitFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAdministrativeUnit,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
