export * from './createIsOddPostRequestBodyFromDiscriminatorValue'
export * from './deserializeIntoIsOddPostRequestBody'
export * from './isOddPostRequestBody'
export * from './isOddRequestBuilderPostRequestConfiguration'
export * from './serializeIsOddPostRequestBody'
