import { createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsFromDiscriminatorValue } from './createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsFromDiscriminatorValue';
import { deserializeIntoBaseCollectionPaginationCountResponse } from './deserializeIntoBaseCollectionPaginationCountResponse';
import { serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails } from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function deserializeIntoUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse(userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse),
        "value": n => { userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse.value = n.getCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails>(createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsFromDiscriminatorValue); },
    }
}
