import { createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdFromDiscriminatorValue } from './createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdFromDiscriminatorValue';
import { deserializeIntoBaseCollectionPaginationCountResponse } from './deserializeIntoBaseCollectionPaginationCountResponse';
import { serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId } from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function deserializeIntoUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse(userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse),
        "value": n => { userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse.value = n.getCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId>(createUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdFromDiscriminatorValue); },
    }
}
