// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoBaseCollectionPaginationCountResponse, serializeBaseCollectionPaginationCountResponse, type BaseCollectionPaginationCountResponse } from './baseCollectionPaginationCountResponse';
import { createEducationAssignmentFromDiscriminatorValue, serializeEducationAssignment, type EducationAssignment } from './educationAssignment';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createEducationAssignmentCollectionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoEducationAssignmentCollectionResponse;
}
export function deserializeIntoEducationAssignmentCollectionResponse(educationAssignmentCollectionResponse: EducationAssignmentCollectionResponse | undefined = {} as EducationAssignmentCollectionResponse) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoBaseCollectionPaginationCountResponse(educationAssignmentCollectionResponse),
        "value": n => { educationAssignmentCollectionResponse.value = n.getCollectionOfObjectValues<EducationAssignment>(createEducationAssignmentFromDiscriminatorValue); },
    }
}
export interface EducationAssignmentCollectionResponse extends BaseCollectionPaginationCountResponse, Parsable {
    /**
     * The value property
     */
    value?: EducationAssignment[];
}
export function serializeEducationAssignmentCollectionResponse(writer: SerializationWriter, educationAssignmentCollectionResponse: EducationAssignmentCollectionResponse | undefined = {} as EducationAssignmentCollectionResponse) : void {
    serializeBaseCollectionPaginationCountResponse(writer, educationAssignmentCollectionResponse)
    writer.writeCollectionOfObjectValues<EducationAssignment>("value", educationAssignmentCollectionResponse.value, serializeEducationAssignment);
}
// tslint:enable
// eslint-enable
