// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createEducationOutcomeFromDiscriminatorValue, serializeEducationOutcome, type EducationOutcome } from './educationOutcome';
import { createEducationSubmissionRecipientFromDiscriminatorValue, serializeEducationSubmissionRecipient, type EducationSubmissionRecipient } from './educationSubmissionRecipient';
import { createEducationSubmissionResourceFromDiscriminatorValue, serializeEducationSubmissionResource, type EducationSubmissionResource } from './educationSubmissionResource';
import { EducationSubmissionStatus } from './educationSubmissionStatus';
import { deserializeIntoEntity, serializeEntity, type Entity } from './entity';
import { createIdentitySetFromDiscriminatorValue, serializeIdentitySet, type IdentitySet } from './identitySet';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createEducationSubmissionFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoEducationSubmission;
}
export function deserializeIntoEducationSubmission(educationSubmission: EducationSubmission | undefined = {} as EducationSubmission) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoEntity(educationSubmission),
        "outcomes": n => { educationSubmission.outcomes = n.getCollectionOfObjectValues<EducationOutcome>(createEducationOutcomeFromDiscriminatorValue); },
        "reassignedBy": n => { educationSubmission.reassignedBy = n.getObjectValue<IdentitySet>(createIdentitySetFromDiscriminatorValue); },
        "reassignedDateTime": n => { educationSubmission.reassignedDateTime = n.getDateValue(); },
        "recipient": n => { educationSubmission.recipient = n.getObjectValue<EducationSubmissionRecipient>(createEducationSubmissionRecipientFromDiscriminatorValue); },
        "resources": n => { educationSubmission.resources = n.getCollectionOfObjectValues<EducationSubmissionResource>(createEducationSubmissionResourceFromDiscriminatorValue); },
        "resourcesFolderUrl": n => { educationSubmission.resourcesFolderUrl = n.getStringValue(); },
        "returnedBy": n => { educationSubmission.returnedBy = n.getObjectValue<IdentitySet>(createIdentitySetFromDiscriminatorValue); },
        "returnedDateTime": n => { educationSubmission.returnedDateTime = n.getDateValue(); },
        "status": n => { educationSubmission.status = n.getEnumValue<EducationSubmissionStatus>(EducationSubmissionStatus); },
        "submittedBy": n => { educationSubmission.submittedBy = n.getObjectValue<IdentitySet>(createIdentitySetFromDiscriminatorValue); },
        "submittedDateTime": n => { educationSubmission.submittedDateTime = n.getDateValue(); },
        "submittedResources": n => { educationSubmission.submittedResources = n.getCollectionOfObjectValues<EducationSubmissionResource>(createEducationSubmissionResourceFromDiscriminatorValue); },
        "unsubmittedBy": n => { educationSubmission.unsubmittedBy = n.getObjectValue<IdentitySet>(createIdentitySetFromDiscriminatorValue); },
        "unsubmittedDateTime": n => { educationSubmission.unsubmittedDateTime = n.getDateValue(); },
    }
}
export interface EducationSubmission extends Entity, Parsable {
    /**
     * The outcomes property
     */
    outcomes?: EducationOutcome[];
    /**
     * User who moved the status of this submission to reassigned.
     */
    reassignedBy?: IdentitySet;
    /**
     * Moment in time when the submission was reassigned. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
     */
    reassignedDateTime?: Date;
    /**
     * Who this submission is assigned to.
     */
    recipient?: EducationSubmissionRecipient;
    /**
     * The resources property
     */
    resources?: EducationSubmissionResource[];
    /**
     * Folder where all file resources for this submission need to be stored.
     */
    resourcesFolderUrl?: string;
    /**
     * User who moved the status of this submission to returned.
     */
    returnedBy?: IdentitySet;
    /**
     * Moment in time when the submission was returned. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
     */
    returnedDateTime?: Date;
    /**
     * Read-only. Possible values are: working, submitted, returned, and reassigned. Note that you must use the Prefer: include-unknown-enum-members request header to get the following value(s) in this evolvable enum: reassigned.
     */
    status?: EducationSubmissionStatus;
    /**
     * User who moved the resource into the submitted state.
     */
    submittedBy?: IdentitySet;
    /**
     * Moment in time when the submission was moved into the submitted state. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
     */
    submittedDateTime?: Date;
    /**
     * The submittedResources property
     */
    submittedResources?: EducationSubmissionResource[];
    /**
     * User who moved the resource from submitted into the working state.
     */
    unsubmittedBy?: IdentitySet;
    /**
     * Moment in time when the submission was moved from submitted into the working state. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
     */
    unsubmittedDateTime?: Date;
}
export function serializeEducationSubmission(writer: SerializationWriter, educationSubmission: EducationSubmission | undefined = {} as EducationSubmission) : void {
        serializeEntity(writer, educationSubmission)
        writer.writeCollectionOfObjectValues<EducationOutcome>("outcomes", educationSubmission.outcomes, );
        writer.writeObjectValue<EducationSubmissionRecipient>("recipient", educationSubmission.recipient, );
        writer.writeCollectionOfObjectValues<EducationSubmissionResource>("resources", educationSubmission.resources, );
        writer.writeCollectionOfObjectValues<EducationSubmissionResource>("submittedResources", educationSubmission.submittedResources, );
}
// tslint:enable
// eslint-enable
