// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createLookupColumnFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoLookupColumn;
}
export function deserializeIntoLookupColumn(lookupColumn: LookupColumn | undefined = {} as LookupColumn) : Record<string, (node: ParseNode) => void> {
    return {
        "allowMultipleValues": n => { lookupColumn.allowMultipleValues = n.getBooleanValue(); },
        "allowUnlimitedLength": n => { lookupColumn.allowUnlimitedLength = n.getBooleanValue(); },
        "columnName": n => { lookupColumn.columnName = n.getStringValue(); },
        "listId": n => { lookupColumn.listId = n.getStringValue(); },
        "@odata.type": n => { lookupColumn.odataType = n.getStringValue(); },
        "primaryLookupColumnId": n => { lookupColumn.primaryLookupColumnId = n.getStringValue(); },
    }
}
export interface LookupColumn extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Indicates whether multiple values can be selected from the source.
     */
    allowMultipleValues?: boolean;
    /**
     * Indicates whether values in the column should be able to exceed the standard limit of 255 characters.
     */
    allowUnlimitedLength?: boolean;
    /**
     * The name of the lookup source column.
     */
    columnName?: string;
    /**
     * The unique identifier of the lookup source list.
     */
    listId?: string;
    /**
     * The OdataType property
     */
    odataType?: string;
    /**
     * If specified, this column is a secondary lookup, pulling an additional field from the list item looked up by the primary lookup. Use the list item looked up by the primary as the source for the column named here.
     */
    primaryLookupColumnId?: string;
}
export function serializeLookupColumn(writer: SerializationWriter, lookupColumn: LookupColumn | undefined = {} as LookupColumn) : void {
        writer.writeBooleanValue("allowMultipleValues", lookupColumn.allowMultipleValues);
        writer.writeBooleanValue("allowUnlimitedLength", lookupColumn.allowUnlimitedLength);
        writer.writeStringValue("columnName", lookupColumn.columnName);
        writer.writeStringValue("listId", lookupColumn.listId);
        writer.writeStringValue("@odata.type", lookupColumn.odataType);
        writer.writeStringValue("primaryLookupColumnId", lookupColumn.primaryLookupColumnId);
        writer.writeAdditionalData(lookupColumn.additionalData);
}
// tslint:enable
// eslint-enable
