import {DefenderCloudBlockLevelType} from './defenderCloudBlockLevelType';
import {DefenderDetectedMalwareActions} from './defenderDetectedMalwareActions';
import {DefenderMonitorFileActivity} from './defenderMonitorFileActivity';
import {DefenderPromptForSampleSubmission} from './defenderPromptForSampleSubmission';
import {DefenderScanType} from './defenderScanType';
import {DiagnosticDataSubmissionMode} from './diagnosticDataSubmissionMode';
import {EdgeCookiePolicy} from './edgeCookiePolicy';
import {EdgeSearchEngineBase} from './edgeSearchEngineBase';
import {RequiredPasswordType} from './requiredPasswordType';
import {SafeSearchFilterType} from './safeSearchFilterType';
import {serializeDefenderDetectedMalwareActions} from './serializeDefenderDetectedMalwareActions';
import {serializeDeviceConfiguration} from './serializeDeviceConfiguration';
import {serializeEdgeSearchEngineBase} from './serializeEdgeSearchEngineBase';
import {serializeWindows10NetworkProxyServer} from './serializeWindows10NetworkProxyServer';
import {StateManagementSetting} from './stateManagementSetting';
import {VisibilitySetting} from './visibilitySetting';
import {WeeklySchedule} from './weeklySchedule';
import {Windows10GeneralConfiguration} from './windows10GeneralConfiguration';
import {Windows10NetworkProxyServer} from './windows10NetworkProxyServer';
import {WindowsSpotlightEnablementSettings} from './windowsSpotlightEnablementSettings';
import {WindowsStartMenuAppListVisibilityType} from './windowsStartMenuAppListVisibilityType';
import {WindowsStartMenuModeType} from './windowsStartMenuModeType';
import {Parsable, ParseNode, SerializationWriter, TimeOnly} from '@microsoft/kiota-abstractions';

export function serializeWindows10GeneralConfiguration(writer: SerializationWriter, windows10GeneralConfiguration: Windows10GeneralConfiguration | undefined = {} as Windows10GeneralConfiguration) : void {
        serializeDeviceConfiguration(writer, windows10GeneralConfiguration)
        writer.writeBooleanValue("accountsBlockAddingNonMicrosoftAccountEmail", windows10GeneralConfiguration.accountsBlockAddingNonMicrosoftAccountEmail);
        writer.writeBooleanValue("antiTheftModeBlocked", windows10GeneralConfiguration.antiTheftModeBlocked);
        writer.writeEnumValue<StateManagementSetting>("appsAllowTrustedAppsSideloading", windows10GeneralConfiguration.appsAllowTrustedAppsSideloading);
        writer.writeBooleanValue("appsBlockWindowsStoreOriginatedApps", windows10GeneralConfiguration.appsBlockWindowsStoreOriginatedApps);
        writer.writeCollectionOfPrimitiveValues<string>("bluetoothAllowedServices", windows10GeneralConfiguration.bluetoothAllowedServices);
        writer.writeBooleanValue("bluetoothBlockAdvertising", windows10GeneralConfiguration.bluetoothBlockAdvertising);
        writer.writeBooleanValue("bluetoothBlockDiscoverableMode", windows10GeneralConfiguration.bluetoothBlockDiscoverableMode);
        writer.writeBooleanValue("bluetoothBlocked", windows10GeneralConfiguration.bluetoothBlocked);
        writer.writeBooleanValue("bluetoothBlockPrePairing", windows10GeneralConfiguration.bluetoothBlockPrePairing);
        writer.writeBooleanValue("cameraBlocked", windows10GeneralConfiguration.cameraBlocked);
        writer.writeBooleanValue("cellularBlockDataWhenRoaming", windows10GeneralConfiguration.cellularBlockDataWhenRoaming);
        writer.writeBooleanValue("cellularBlockVpn", windows10GeneralConfiguration.cellularBlockVpn);
        writer.writeBooleanValue("cellularBlockVpnWhenRoaming", windows10GeneralConfiguration.cellularBlockVpnWhenRoaming);
        writer.writeBooleanValue("certificatesBlockManualRootCertificateInstallation", windows10GeneralConfiguration.certificatesBlockManualRootCertificateInstallation);
        writer.writeBooleanValue("connectedDevicesServiceBlocked", windows10GeneralConfiguration.connectedDevicesServiceBlocked);
        writer.writeBooleanValue("copyPasteBlocked", windows10GeneralConfiguration.copyPasteBlocked);
        writer.writeBooleanValue("cortanaBlocked", windows10GeneralConfiguration.cortanaBlocked);
        writer.writeBooleanValue("defenderBlockEndUserAccess", windows10GeneralConfiguration.defenderBlockEndUserAccess);
        writer.writeEnumValue<DefenderCloudBlockLevelType>("defenderCloudBlockLevel", windows10GeneralConfiguration.defenderCloudBlockLevel);
        writer.writeNumberValue("defenderDaysBeforeDeletingQuarantinedMalware", windows10GeneralConfiguration.defenderDaysBeforeDeletingQuarantinedMalware);
        writer.writeObjectValue<DefenderDetectedMalwareActions>("defenderDetectedMalwareActions", windows10GeneralConfiguration.defenderDetectedMalwareActions, serializeDefenderDetectedMalwareActions);
        writer.writeCollectionOfPrimitiveValues<string>("defenderFileExtensionsToExclude", windows10GeneralConfiguration.defenderFileExtensionsToExclude);
        writer.writeCollectionOfPrimitiveValues<string>("defenderFilesAndFoldersToExclude", windows10GeneralConfiguration.defenderFilesAndFoldersToExclude);
        writer.writeEnumValue<DefenderMonitorFileActivity>("defenderMonitorFileActivity", windows10GeneralConfiguration.defenderMonitorFileActivity);
        writer.writeCollectionOfPrimitiveValues<string>("defenderProcessesToExclude", windows10GeneralConfiguration.defenderProcessesToExclude);
        writer.writeEnumValue<DefenderPromptForSampleSubmission>("defenderPromptForSampleSubmission", windows10GeneralConfiguration.defenderPromptForSampleSubmission);
        writer.writeBooleanValue("defenderRequireBehaviorMonitoring", windows10GeneralConfiguration.defenderRequireBehaviorMonitoring);
        writer.writeBooleanValue("defenderRequireCloudProtection", windows10GeneralConfiguration.defenderRequireCloudProtection);
        writer.writeBooleanValue("defenderRequireNetworkInspectionSystem", windows10GeneralConfiguration.defenderRequireNetworkInspectionSystem);
        writer.writeBooleanValue("defenderRequireRealTimeMonitoring", windows10GeneralConfiguration.defenderRequireRealTimeMonitoring);
        writer.writeBooleanValue("defenderScanArchiveFiles", windows10GeneralConfiguration.defenderScanArchiveFiles);
        writer.writeBooleanValue("defenderScanDownloads", windows10GeneralConfiguration.defenderScanDownloads);
        writer.writeBooleanValue("defenderScanIncomingMail", windows10GeneralConfiguration.defenderScanIncomingMail);
        writer.writeBooleanValue("defenderScanMappedNetworkDrivesDuringFullScan", windows10GeneralConfiguration.defenderScanMappedNetworkDrivesDuringFullScan);
        writer.writeNumberValue("defenderScanMaxCpu", windows10GeneralConfiguration.defenderScanMaxCpu);
        writer.writeBooleanValue("defenderScanNetworkFiles", windows10GeneralConfiguration.defenderScanNetworkFiles);
        writer.writeBooleanValue("defenderScanRemovableDrivesDuringFullScan", windows10GeneralConfiguration.defenderScanRemovableDrivesDuringFullScan);
        writer.writeBooleanValue("defenderScanScriptsLoadedInInternetExplorer", windows10GeneralConfiguration.defenderScanScriptsLoadedInInternetExplorer);
        writer.writeEnumValue<DefenderScanType>("defenderScanType", windows10GeneralConfiguration.defenderScanType);
        writer.writeTimeOnlyValue("defenderScheduledQuickScanTime", windows10GeneralConfiguration.defenderScheduledQuickScanTime);
        writer.writeTimeOnlyValue("defenderScheduledScanTime", windows10GeneralConfiguration.defenderScheduledScanTime);
        writer.writeNumberValue("defenderSignatureUpdateIntervalInHours", windows10GeneralConfiguration.defenderSignatureUpdateIntervalInHours);
        writer.writeEnumValue<WeeklySchedule>("defenderSystemScanSchedule", windows10GeneralConfiguration.defenderSystemScanSchedule);
        writer.writeEnumValue<StateManagementSetting>("developerUnlockSetting", windows10GeneralConfiguration.developerUnlockSetting);
        writer.writeBooleanValue("deviceManagementBlockFactoryResetOnMobile", windows10GeneralConfiguration.deviceManagementBlockFactoryResetOnMobile);
        writer.writeBooleanValue("deviceManagementBlockManualUnenroll", windows10GeneralConfiguration.deviceManagementBlockManualUnenroll);
        writer.writeEnumValue<DiagnosticDataSubmissionMode>("diagnosticsDataSubmissionMode", windows10GeneralConfiguration.diagnosticsDataSubmissionMode);
        writer.writeBooleanValue("edgeAllowStartPagesModification", windows10GeneralConfiguration.edgeAllowStartPagesModification);
        writer.writeBooleanValue("edgeBlockAccessToAboutFlags", windows10GeneralConfiguration.edgeBlockAccessToAboutFlags);
        writer.writeBooleanValue("edgeBlockAddressBarDropdown", windows10GeneralConfiguration.edgeBlockAddressBarDropdown);
        writer.writeBooleanValue("edgeBlockAutofill", windows10GeneralConfiguration.edgeBlockAutofill);
        writer.writeBooleanValue("edgeBlockCompatibilityList", windows10GeneralConfiguration.edgeBlockCompatibilityList);
        writer.writeBooleanValue("edgeBlockDeveloperTools", windows10GeneralConfiguration.edgeBlockDeveloperTools);
        writer.writeBooleanValue("edgeBlocked", windows10GeneralConfiguration.edgeBlocked);
        writer.writeBooleanValue("edgeBlockExtensions", windows10GeneralConfiguration.edgeBlockExtensions);
        writer.writeBooleanValue("edgeBlockInPrivateBrowsing", windows10GeneralConfiguration.edgeBlockInPrivateBrowsing);
        writer.writeBooleanValue("edgeBlockJavaScript", windows10GeneralConfiguration.edgeBlockJavaScript);
        writer.writeBooleanValue("edgeBlockLiveTileDataCollection", windows10GeneralConfiguration.edgeBlockLiveTileDataCollection);
        writer.writeBooleanValue("edgeBlockPasswordManager", windows10GeneralConfiguration.edgeBlockPasswordManager);
        writer.writeBooleanValue("edgeBlockPopups", windows10GeneralConfiguration.edgeBlockPopups);
        writer.writeBooleanValue("edgeBlockSearchSuggestions", windows10GeneralConfiguration.edgeBlockSearchSuggestions);
        writer.writeBooleanValue("edgeBlockSendingDoNotTrackHeader", windows10GeneralConfiguration.edgeBlockSendingDoNotTrackHeader);
        writer.writeBooleanValue("edgeBlockSendingIntranetTrafficToInternetExplorer", windows10GeneralConfiguration.edgeBlockSendingIntranetTrafficToInternetExplorer);
        writer.writeBooleanValue("edgeClearBrowsingDataOnExit", windows10GeneralConfiguration.edgeClearBrowsingDataOnExit);
        writer.writeEnumValue<EdgeCookiePolicy>("edgeCookiePolicy", windows10GeneralConfiguration.edgeCookiePolicy);
        writer.writeBooleanValue("edgeDisableFirstRunPage", windows10GeneralConfiguration.edgeDisableFirstRunPage);
        writer.writeStringValue("edgeEnterpriseModeSiteListLocation", windows10GeneralConfiguration.edgeEnterpriseModeSiteListLocation);
        writer.writeStringValue("edgeFirstRunUrl", windows10GeneralConfiguration.edgeFirstRunUrl);
        writer.writeCollectionOfPrimitiveValues<string>("edgeHomepageUrls", windows10GeneralConfiguration.edgeHomepageUrls);
        writer.writeBooleanValue("edgeRequireSmartScreen", windows10GeneralConfiguration.edgeRequireSmartScreen);
        writer.writeObjectValue<EdgeSearchEngineBase>("edgeSearchEngine", windows10GeneralConfiguration.edgeSearchEngine, serializeEdgeSearchEngineBase);
        writer.writeBooleanValue("edgeSendIntranetTrafficToInternetExplorer", windows10GeneralConfiguration.edgeSendIntranetTrafficToInternetExplorer);
        writer.writeBooleanValue("edgeSyncFavoritesWithInternetExplorer", windows10GeneralConfiguration.edgeSyncFavoritesWithInternetExplorer);
        writer.writeStringValue("enterpriseCloudPrintDiscoveryEndPoint", windows10GeneralConfiguration.enterpriseCloudPrintDiscoveryEndPoint);
        writer.writeNumberValue("enterpriseCloudPrintDiscoveryMaxLimit", windows10GeneralConfiguration.enterpriseCloudPrintDiscoveryMaxLimit);
        writer.writeStringValue("enterpriseCloudPrintMopriaDiscoveryResourceIdentifier", windows10GeneralConfiguration.enterpriseCloudPrintMopriaDiscoveryResourceIdentifier);
        writer.writeStringValue("enterpriseCloudPrintOAuthAuthority", windows10GeneralConfiguration.enterpriseCloudPrintOAuthAuthority);
        writer.writeStringValue("enterpriseCloudPrintOAuthClientIdentifier", windows10GeneralConfiguration.enterpriseCloudPrintOAuthClientIdentifier);
        writer.writeStringValue("enterpriseCloudPrintResourceIdentifier", windows10GeneralConfiguration.enterpriseCloudPrintResourceIdentifier);
        writer.writeBooleanValue("experienceBlockDeviceDiscovery", windows10GeneralConfiguration.experienceBlockDeviceDiscovery);
        writer.writeBooleanValue("experienceBlockErrorDialogWhenNoSIM", windows10GeneralConfiguration.experienceBlockErrorDialogWhenNoSIM);
        writer.writeBooleanValue("experienceBlockTaskSwitcher", windows10GeneralConfiguration.experienceBlockTaskSwitcher);
        writer.writeBooleanValue("gameDvrBlocked", windows10GeneralConfiguration.gameDvrBlocked);
        writer.writeBooleanValue("internetSharingBlocked", windows10GeneralConfiguration.internetSharingBlocked);
        writer.writeBooleanValue("locationServicesBlocked", windows10GeneralConfiguration.locationServicesBlocked);
        writer.writeBooleanValue("lockScreenAllowTimeoutConfiguration", windows10GeneralConfiguration.lockScreenAllowTimeoutConfiguration);
        writer.writeBooleanValue("lockScreenBlockActionCenterNotifications", windows10GeneralConfiguration.lockScreenBlockActionCenterNotifications);
        writer.writeBooleanValue("lockScreenBlockCortana", windows10GeneralConfiguration.lockScreenBlockCortana);
        writer.writeBooleanValue("lockScreenBlockToastNotifications", windows10GeneralConfiguration.lockScreenBlockToastNotifications);
        writer.writeNumberValue("lockScreenTimeoutInSeconds", windows10GeneralConfiguration.lockScreenTimeoutInSeconds);
        writer.writeBooleanValue("logonBlockFastUserSwitching", windows10GeneralConfiguration.logonBlockFastUserSwitching);
        writer.writeBooleanValue("microsoftAccountBlocked", windows10GeneralConfiguration.microsoftAccountBlocked);
        writer.writeBooleanValue("microsoftAccountBlockSettingsSync", windows10GeneralConfiguration.microsoftAccountBlockSettingsSync);
        writer.writeBooleanValue("networkProxyApplySettingsDeviceWide", windows10GeneralConfiguration.networkProxyApplySettingsDeviceWide);
        writer.writeStringValue("networkProxyAutomaticConfigurationUrl", windows10GeneralConfiguration.networkProxyAutomaticConfigurationUrl);
        writer.writeBooleanValue("networkProxyDisableAutoDetect", windows10GeneralConfiguration.networkProxyDisableAutoDetect);
        writer.writeObjectValue<Windows10NetworkProxyServer>("networkProxyServer", windows10GeneralConfiguration.networkProxyServer, serializeWindows10NetworkProxyServer);
        writer.writeBooleanValue("nfcBlocked", windows10GeneralConfiguration.nfcBlocked);
        writer.writeBooleanValue("oneDriveDisableFileSync", windows10GeneralConfiguration.oneDriveDisableFileSync);
        writer.writeBooleanValue("passwordBlockSimple", windows10GeneralConfiguration.passwordBlockSimple);
        writer.writeNumberValue("passwordExpirationDays", windows10GeneralConfiguration.passwordExpirationDays);
        writer.writeNumberValue("passwordMinimumCharacterSetCount", windows10GeneralConfiguration.passwordMinimumCharacterSetCount);
        writer.writeNumberValue("passwordMinimumLength", windows10GeneralConfiguration.passwordMinimumLength);
        writer.writeNumberValue("passwordMinutesOfInactivityBeforeScreenTimeout", windows10GeneralConfiguration.passwordMinutesOfInactivityBeforeScreenTimeout);
        writer.writeNumberValue("passwordPreviousPasswordBlockCount", windows10GeneralConfiguration.passwordPreviousPasswordBlockCount);
        writer.writeBooleanValue("passwordRequired", windows10GeneralConfiguration.passwordRequired);
        writer.writeEnumValue<RequiredPasswordType>("passwordRequiredType", windows10GeneralConfiguration.passwordRequiredType);
        writer.writeBooleanValue("passwordRequireWhenResumeFromIdleState", windows10GeneralConfiguration.passwordRequireWhenResumeFromIdleState);
        writer.writeNumberValue("passwordSignInFailureCountBeforeFactoryReset", windows10GeneralConfiguration.passwordSignInFailureCountBeforeFactoryReset);
        writer.writeStringValue("personalizationDesktopImageUrl", windows10GeneralConfiguration.personalizationDesktopImageUrl);
        writer.writeStringValue("personalizationLockScreenImageUrl", windows10GeneralConfiguration.personalizationLockScreenImageUrl);
        writer.writeEnumValue<StateManagementSetting>("privacyAdvertisingId", windows10GeneralConfiguration.privacyAdvertisingId);
        writer.writeBooleanValue("privacyAutoAcceptPairingAndConsentPrompts", windows10GeneralConfiguration.privacyAutoAcceptPairingAndConsentPrompts);
        writer.writeBooleanValue("privacyBlockInputPersonalization", windows10GeneralConfiguration.privacyBlockInputPersonalization);
        writer.writeBooleanValue("resetProtectionModeBlocked", windows10GeneralConfiguration.resetProtectionModeBlocked);
        writer.writeEnumValue<SafeSearchFilterType>("safeSearchFilter", windows10GeneralConfiguration.safeSearchFilter);
        writer.writeBooleanValue("screenCaptureBlocked", windows10GeneralConfiguration.screenCaptureBlocked);
        writer.writeBooleanValue("searchBlockDiacritics", windows10GeneralConfiguration.searchBlockDiacritics);
        writer.writeBooleanValue("searchDisableAutoLanguageDetection", windows10GeneralConfiguration.searchDisableAutoLanguageDetection);
        writer.writeBooleanValue("searchDisableIndexerBackoff", windows10GeneralConfiguration.searchDisableIndexerBackoff);
        writer.writeBooleanValue("searchDisableIndexingEncryptedItems", windows10GeneralConfiguration.searchDisableIndexingEncryptedItems);
        writer.writeBooleanValue("searchDisableIndexingRemovableDrive", windows10GeneralConfiguration.searchDisableIndexingRemovableDrive);
        writer.writeBooleanValue("searchEnableAutomaticIndexSizeManangement", windows10GeneralConfiguration.searchEnableAutomaticIndexSizeManangement);
        writer.writeBooleanValue("searchEnableRemoteQueries", windows10GeneralConfiguration.searchEnableRemoteQueries);
        writer.writeBooleanValue("settingsBlockAccountsPage", windows10GeneralConfiguration.settingsBlockAccountsPage);
        writer.writeBooleanValue("settingsBlockAddProvisioningPackage", windows10GeneralConfiguration.settingsBlockAddProvisioningPackage);
        writer.writeBooleanValue("settingsBlockAppsPage", windows10GeneralConfiguration.settingsBlockAppsPage);
        writer.writeBooleanValue("settingsBlockChangeLanguage", windows10GeneralConfiguration.settingsBlockChangeLanguage);
        writer.writeBooleanValue("settingsBlockChangePowerSleep", windows10GeneralConfiguration.settingsBlockChangePowerSleep);
        writer.writeBooleanValue("settingsBlockChangeRegion", windows10GeneralConfiguration.settingsBlockChangeRegion);
        writer.writeBooleanValue("settingsBlockChangeSystemTime", windows10GeneralConfiguration.settingsBlockChangeSystemTime);
        writer.writeBooleanValue("settingsBlockDevicesPage", windows10GeneralConfiguration.settingsBlockDevicesPage);
        writer.writeBooleanValue("settingsBlockEaseOfAccessPage", windows10GeneralConfiguration.settingsBlockEaseOfAccessPage);
        writer.writeBooleanValue("settingsBlockEditDeviceName", windows10GeneralConfiguration.settingsBlockEditDeviceName);
        writer.writeBooleanValue("settingsBlockGamingPage", windows10GeneralConfiguration.settingsBlockGamingPage);
        writer.writeBooleanValue("settingsBlockNetworkInternetPage", windows10GeneralConfiguration.settingsBlockNetworkInternetPage);
        writer.writeBooleanValue("settingsBlockPersonalizationPage", windows10GeneralConfiguration.settingsBlockPersonalizationPage);
        writer.writeBooleanValue("settingsBlockPrivacyPage", windows10GeneralConfiguration.settingsBlockPrivacyPage);
        writer.writeBooleanValue("settingsBlockRemoveProvisioningPackage", windows10GeneralConfiguration.settingsBlockRemoveProvisioningPackage);
        writer.writeBooleanValue("settingsBlockSettingsApp", windows10GeneralConfiguration.settingsBlockSettingsApp);
        writer.writeBooleanValue("settingsBlockSystemPage", windows10GeneralConfiguration.settingsBlockSystemPage);
        writer.writeBooleanValue("settingsBlockTimeLanguagePage", windows10GeneralConfiguration.settingsBlockTimeLanguagePage);
        writer.writeBooleanValue("settingsBlockUpdateSecurityPage", windows10GeneralConfiguration.settingsBlockUpdateSecurityPage);
        writer.writeBooleanValue("sharedUserAppDataAllowed", windows10GeneralConfiguration.sharedUserAppDataAllowed);
        writer.writeBooleanValue("smartScreenBlockPromptOverride", windows10GeneralConfiguration.smartScreenBlockPromptOverride);
        writer.writeBooleanValue("smartScreenBlockPromptOverrideForFiles", windows10GeneralConfiguration.smartScreenBlockPromptOverrideForFiles);
        writer.writeBooleanValue("smartScreenEnableAppInstallControl", windows10GeneralConfiguration.smartScreenEnableAppInstallControl);
        writer.writeBooleanValue("startBlockUnpinningAppsFromTaskbar", windows10GeneralConfiguration.startBlockUnpinningAppsFromTaskbar);
        writer.writeEnumValue<WindowsStartMenuAppListVisibilityType>("startMenuAppListVisibility", windows10GeneralConfiguration.startMenuAppListVisibility);
        writer.writeBooleanValue("startMenuHideChangeAccountSettings", windows10GeneralConfiguration.startMenuHideChangeAccountSettings);
        writer.writeBooleanValue("startMenuHideFrequentlyUsedApps", windows10GeneralConfiguration.startMenuHideFrequentlyUsedApps);
        writer.writeBooleanValue("startMenuHideHibernate", windows10GeneralConfiguration.startMenuHideHibernate);
        writer.writeBooleanValue("startMenuHideLock", windows10GeneralConfiguration.startMenuHideLock);
        writer.writeBooleanValue("startMenuHidePowerButton", windows10GeneralConfiguration.startMenuHidePowerButton);
        writer.writeBooleanValue("startMenuHideRecentJumpLists", windows10GeneralConfiguration.startMenuHideRecentJumpLists);
        writer.writeBooleanValue("startMenuHideRecentlyAddedApps", windows10GeneralConfiguration.startMenuHideRecentlyAddedApps);
        writer.writeBooleanValue("startMenuHideRestartOptions", windows10GeneralConfiguration.startMenuHideRestartOptions);
        writer.writeBooleanValue("startMenuHideShutDown", windows10GeneralConfiguration.startMenuHideShutDown);
        writer.writeBooleanValue("startMenuHideSignOut", windows10GeneralConfiguration.startMenuHideSignOut);
        writer.writeBooleanValue("startMenuHideSleep", windows10GeneralConfiguration.startMenuHideSleep);
        writer.writeBooleanValue("startMenuHideSwitchAccount", windows10GeneralConfiguration.startMenuHideSwitchAccount);
        writer.writeBooleanValue("startMenuHideUserTile", windows10GeneralConfiguration.startMenuHideUserTile);
        writer.writeStringValue("startMenuLayoutEdgeAssetsXml", windows10GeneralConfiguration.startMenuLayoutEdgeAssetsXml);
        writer.writeStringValue("startMenuLayoutXml", windows10GeneralConfiguration.startMenuLayoutXml);
        writer.writeEnumValue<WindowsStartMenuModeType>("startMenuMode", windows10GeneralConfiguration.startMenuMode);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderDocuments", windows10GeneralConfiguration.startMenuPinnedFolderDocuments);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderDownloads", windows10GeneralConfiguration.startMenuPinnedFolderDownloads);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderFileExplorer", windows10GeneralConfiguration.startMenuPinnedFolderFileExplorer);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderHomeGroup", windows10GeneralConfiguration.startMenuPinnedFolderHomeGroup);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderMusic", windows10GeneralConfiguration.startMenuPinnedFolderMusic);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderNetwork", windows10GeneralConfiguration.startMenuPinnedFolderNetwork);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderPersonalFolder", windows10GeneralConfiguration.startMenuPinnedFolderPersonalFolder);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderPictures", windows10GeneralConfiguration.startMenuPinnedFolderPictures);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderSettings", windows10GeneralConfiguration.startMenuPinnedFolderSettings);
        writer.writeEnumValue<VisibilitySetting>("startMenuPinnedFolderVideos", windows10GeneralConfiguration.startMenuPinnedFolderVideos);
        writer.writeBooleanValue("storageBlockRemovableStorage", windows10GeneralConfiguration.storageBlockRemovableStorage);
        writer.writeBooleanValue("storageRequireMobileDeviceEncryption", windows10GeneralConfiguration.storageRequireMobileDeviceEncryption);
        writer.writeBooleanValue("storageRestrictAppDataToSystemVolume", windows10GeneralConfiguration.storageRestrictAppDataToSystemVolume);
        writer.writeBooleanValue("storageRestrictAppInstallToSystemVolume", windows10GeneralConfiguration.storageRestrictAppInstallToSystemVolume);
        writer.writeBooleanValue("tenantLockdownRequireNetworkDuringOutOfBoxExperience", windows10GeneralConfiguration.tenantLockdownRequireNetworkDuringOutOfBoxExperience);
        writer.writeBooleanValue("usbBlocked", windows10GeneralConfiguration.usbBlocked);
        writer.writeBooleanValue("voiceRecordingBlocked", windows10GeneralConfiguration.voiceRecordingBlocked);
        writer.writeBooleanValue("webRtcBlockLocalhostIpAddress", windows10GeneralConfiguration.webRtcBlockLocalhostIpAddress);
        writer.writeBooleanValue("wiFiBlockAutomaticConnectHotspots", windows10GeneralConfiguration.wiFiBlockAutomaticConnectHotspots);
        writer.writeBooleanValue("wiFiBlocked", windows10GeneralConfiguration.wiFiBlocked);
        writer.writeBooleanValue("wiFiBlockManualConfiguration", windows10GeneralConfiguration.wiFiBlockManualConfiguration);
        writer.writeNumberValue("wiFiScanInterval", windows10GeneralConfiguration.wiFiScanInterval);
        writer.writeBooleanValue("windowsSpotlightBlockConsumerSpecificFeatures", windows10GeneralConfiguration.windowsSpotlightBlockConsumerSpecificFeatures);
        writer.writeBooleanValue("windowsSpotlightBlocked", windows10GeneralConfiguration.windowsSpotlightBlocked);
        writer.writeBooleanValue("windowsSpotlightBlockOnActionCenter", windows10GeneralConfiguration.windowsSpotlightBlockOnActionCenter);
        writer.writeBooleanValue("windowsSpotlightBlockTailoredExperiences", windows10GeneralConfiguration.windowsSpotlightBlockTailoredExperiences);
        writer.writeBooleanValue("windowsSpotlightBlockThirdPartyNotifications", windows10GeneralConfiguration.windowsSpotlightBlockThirdPartyNotifications);
        writer.writeBooleanValue("windowsSpotlightBlockWelcomeExperience", windows10GeneralConfiguration.windowsSpotlightBlockWelcomeExperience);
        writer.writeBooleanValue("windowsSpotlightBlockWindowsTips", windows10GeneralConfiguration.windowsSpotlightBlockWindowsTips);
        writer.writeEnumValue<WindowsSpotlightEnablementSettings>("windowsSpotlightConfigureOnLockScreen", windows10GeneralConfiguration.windowsSpotlightConfigureOnLockScreen);
        writer.writeBooleanValue("windowsStoreBlockAutoUpdate", windows10GeneralConfiguration.windowsStoreBlockAutoUpdate);
        writer.writeBooleanValue("windowsStoreBlocked", windows10GeneralConfiguration.windowsStoreBlocked);
        writer.writeBooleanValue("windowsStoreEnablePrivateStoreOnly", windows10GeneralConfiguration.windowsStoreEnablePrivateStoreOnly);
        writer.writeBooleanValue("wirelessDisplayBlockProjectionToThisDevice", windows10GeneralConfiguration.wirelessDisplayBlockProjectionToThisDevice);
        writer.writeBooleanValue("wirelessDisplayBlockUserInputFromReceiver", windows10GeneralConfiguration.wirelessDisplayBlockUserInputFromReceiver);
        writer.writeBooleanValue("wirelessDisplayRequirePinForPairing", windows10GeneralConfiguration.wirelessDisplayRequirePinForPairing);
}
