import {serializeBaseCollectionPaginationCountResponse} from './serializeBaseCollectionPaginationCountResponse';
import {serializeWindowsInformationProtectionNetworkLearningSummary} from './serializeWindowsInformationProtectionNetworkLearningSummary';
import type {WindowsInformationProtectionNetworkLearningSummary} from './windowsInformationProtectionNetworkLearningSummary';
import type {WindowsInformationProtectionNetworkLearningSummaryCollectionResponse} from './windowsInformationProtectionNetworkLearningSummaryCollectionResponse';
import type {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeWindowsInformationProtectionNetworkLearningSummaryCollectionResponse(writer: SerializationWriter, windowsInformationProtectionNetworkLearningSummaryCollectionResponse: WindowsInformationProtectionNetworkLearningSummaryCollectionResponse | undefined = {} as WindowsInformationProtectionNetworkLearningSummaryCollectionResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, windowsInformationProtectionNetworkLearningSummaryCollectionResponse)
        writer.writeCollectionOfObjectValues<WindowsInformationProtectionNetworkLearningSummary>("value", windowsInformationProtectionNetworkLearningSummaryCollectionResponse.value, serializeWindowsInformationProtectionNetworkLearningSummary);
}
