import {serializeBaseCollectionPaginationCountResponse} from './serializeBaseCollectionPaginationCountResponse';
import {serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId} from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId';
import {UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId} from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId';
import {UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse} from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse(writer: SerializationWriter, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse)
        writer.writeCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId>("value", userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceIdCollectionResponse.value, serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId);
}
