import { serializeBaseCollectionPaginationCountResponse } from './serializeBaseCollectionPaginationCountResponse';
import { serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails } from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import { type UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse } from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse(writer: SerializationWriter, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse)
        writer.writeCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails>("value", userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse.value, serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails);
}
