import {serializeBaseCollectionPaginationCountResponse} from './serializeBaseCollectionPaginationCountResponse';
import {serializeUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion} from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion';
import type {UserExperienceAnalyticsAppHealthAppPerformanceByOSVersion} from './userExperienceAnalyticsAppHealthAppPerformanceByOSVersion';
import type {UserExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse} from './userExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeUserExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse(writer: SerializationWriter, userExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, userExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse)
        writer.writeCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByOSVersion>("value", userExperienceAnalyticsAppHealthAppPerformanceByOSVersionCollectionResponse.value, serializeUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion);
}
