import {ApplePushNotificationCertificate} from './applePushNotificationCertificate';
import {AuditEvent} from './auditEvent';
import {ComplianceManagementPartner} from './complianceManagementPartner';
import {DetectedApp} from './detectedApp';
import {DeviceAndAppManagementRoleAssignment} from './deviceAndAppManagementRoleAssignment';
import {DeviceCategory} from './deviceCategory';
import {DeviceCompliancePolicy} from './deviceCompliancePolicy';
import {DeviceCompliancePolicyDeviceStateSummary} from './deviceCompliancePolicyDeviceStateSummary';
import {DeviceCompliancePolicySettingStateSummary} from './deviceCompliancePolicySettingStateSummary';
import {DeviceConfiguration} from './deviceConfiguration';
import {DeviceConfigurationDeviceStateSummary} from './deviceConfigurationDeviceStateSummary';
import {DeviceEnrollmentConfiguration} from './deviceEnrollmentConfiguration';
import {DeviceManagement} from './deviceManagement';
import {DeviceManagementExchangeConnector} from './deviceManagementExchangeConnector';
import {DeviceManagementPartner} from './deviceManagementPartner';
import {DeviceManagementReports} from './deviceManagementReports';
import {DeviceManagementSettings} from './deviceManagementSettings';
import {DeviceManagementSubscriptionState} from './deviceManagementSubscriptionState';
import {DeviceManagementTroubleshootingEvent} from './deviceManagementTroubleshootingEvent';
import {ImportedWindowsAutopilotDeviceIdentity} from './importedWindowsAutopilotDeviceIdentity';
import {IntuneBrand} from './intuneBrand';
import {IosUpdateDeviceStatus} from './iosUpdateDeviceStatus';
import {ManagedDevice} from './managedDevice';
import {ManagedDeviceOverview} from './managedDeviceOverview';
import {MobileThreatDefenseConnector} from './mobileThreatDefenseConnector';
import {NotificationMessageTemplate} from './notificationMessageTemplate';
import {OnPremisesConditionalAccessSettings} from './onPremisesConditionalAccessSettings';
import {RemoteAssistancePartner} from './remoteAssistancePartner';
import {ResourceOperation} from './resourceOperation';
import {RoleDefinition} from './roleDefinition';
import {serializeApplePushNotificationCertificate} from './serializeApplePushNotificationCertificate';
import {serializeAuditEvent} from './serializeAuditEvent';
import {serializeComplianceManagementPartner} from './serializeComplianceManagementPartner';
import {serializeDetectedApp} from './serializeDetectedApp';
import {serializeDeviceAndAppManagementRoleAssignment} from './serializeDeviceAndAppManagementRoleAssignment';
import {serializeDeviceCategory} from './serializeDeviceCategory';
import {serializeDeviceCompliancePolicy} from './serializeDeviceCompliancePolicy';
import {serializeDeviceCompliancePolicyDeviceStateSummary} from './serializeDeviceCompliancePolicyDeviceStateSummary';
import {serializeDeviceCompliancePolicySettingStateSummary} from './serializeDeviceCompliancePolicySettingStateSummary';
import {serializeDeviceConfiguration} from './serializeDeviceConfiguration';
import {serializeDeviceConfigurationDeviceStateSummary} from './serializeDeviceConfigurationDeviceStateSummary';
import {serializeDeviceEnrollmentConfiguration} from './serializeDeviceEnrollmentConfiguration';
import {serializeDeviceManagementExchangeConnector} from './serializeDeviceManagementExchangeConnector';
import {serializeDeviceManagementPartner} from './serializeDeviceManagementPartner';
import {serializeDeviceManagementReports} from './serializeDeviceManagementReports';
import {serializeDeviceManagementSettings} from './serializeDeviceManagementSettings';
import {serializeDeviceManagementTroubleshootingEvent} from './serializeDeviceManagementTroubleshootingEvent';
import {serializeEntity} from './serializeEntity';
import {serializeImportedWindowsAutopilotDeviceIdentity} from './serializeImportedWindowsAutopilotDeviceIdentity';
import {serializeIntuneBrand} from './serializeIntuneBrand';
import {serializeIosUpdateDeviceStatus} from './serializeIosUpdateDeviceStatus';
import {serializeManagedDevice} from './serializeManagedDevice';
import {serializeManagedDeviceOverview} from './serializeManagedDeviceOverview';
import {serializeMobileThreatDefenseConnector} from './serializeMobileThreatDefenseConnector';
import {serializeNotificationMessageTemplate} from './serializeNotificationMessageTemplate';
import {serializeOnPremisesConditionalAccessSettings} from './serializeOnPremisesConditionalAccessSettings';
import {serializeRemoteAssistancePartner} from './serializeRemoteAssistancePartner';
import {serializeResourceOperation} from './serializeResourceOperation';
import {serializeRoleDefinition} from './serializeRoleDefinition';
import {serializeSoftwareUpdateStatusSummary} from './serializeSoftwareUpdateStatusSummary';
import {serializeTelecomExpenseManagementPartner} from './serializeTelecomExpenseManagementPartner';
import {serializeTermsAndConditions} from './serializeTermsAndConditions';
import {serializeWindowsAutopilotDeviceIdentity} from './serializeWindowsAutopilotDeviceIdentity';
import {serializeWindowsInformationProtectionAppLearningSummary} from './serializeWindowsInformationProtectionAppLearningSummary';
import {serializeWindowsInformationProtectionNetworkLearningSummary} from './serializeWindowsInformationProtectionNetworkLearningSummary';
import {SoftwareUpdateStatusSummary} from './softwareUpdateStatusSummary';
import {TelecomExpenseManagementPartner} from './telecomExpenseManagementPartner';
import {TermsAndConditions} from './termsAndConditions';
import {WindowsAutopilotDeviceIdentity} from './windowsAutopilotDeviceIdentity';
import {WindowsInformationProtectionAppLearningSummary} from './windowsInformationProtectionAppLearningSummary';
import {WindowsInformationProtectionNetworkLearningSummary} from './windowsInformationProtectionNetworkLearningSummary';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeDeviceManagement(writer: SerializationWriter, deviceManagement: DeviceManagement | undefined = {} as DeviceManagement) : void {
        serializeEntity(writer, deviceManagement)
        writer.writeObjectValue<ApplePushNotificationCertificate>("applePushNotificationCertificate", deviceManagement.applePushNotificationCertificate, serializeApplePushNotificationCertificate);
        writer.writeCollectionOfObjectValues<AuditEvent>("auditEvents", deviceManagement.auditEvents, serializeAuditEvent);
        writer.writeCollectionOfObjectValues<ComplianceManagementPartner>("complianceManagementPartners", deviceManagement.complianceManagementPartners, serializeComplianceManagementPartner);
        writer.writeObjectValue<OnPremisesConditionalAccessSettings>("conditionalAccessSettings", deviceManagement.conditionalAccessSettings, serializeOnPremisesConditionalAccessSettings);
        writer.writeCollectionOfObjectValues<DetectedApp>("detectedApps", deviceManagement.detectedApps, serializeDetectedApp);
        writer.writeCollectionOfObjectValues<DeviceCategory>("deviceCategories", deviceManagement.deviceCategories, serializeDeviceCategory);
        writer.writeCollectionOfObjectValues<DeviceCompliancePolicy>("deviceCompliancePolicies", deviceManagement.deviceCompliancePolicies, serializeDeviceCompliancePolicy);
        writer.writeObjectValue<DeviceCompliancePolicyDeviceStateSummary>("deviceCompliancePolicyDeviceStateSummary", deviceManagement.deviceCompliancePolicyDeviceStateSummary, serializeDeviceCompliancePolicyDeviceStateSummary);
        writer.writeCollectionOfObjectValues<DeviceCompliancePolicySettingStateSummary>("deviceCompliancePolicySettingStateSummaries", deviceManagement.deviceCompliancePolicySettingStateSummaries, serializeDeviceCompliancePolicySettingStateSummary);
        writer.writeObjectValue<DeviceConfigurationDeviceStateSummary>("deviceConfigurationDeviceStateSummaries", deviceManagement.deviceConfigurationDeviceStateSummaries, serializeDeviceConfigurationDeviceStateSummary);
        writer.writeCollectionOfObjectValues<DeviceConfiguration>("deviceConfigurations", deviceManagement.deviceConfigurations, serializeDeviceConfiguration);
        writer.writeCollectionOfObjectValues<DeviceEnrollmentConfiguration>("deviceEnrollmentConfigurations", deviceManagement.deviceEnrollmentConfigurations, serializeDeviceEnrollmentConfiguration);
        writer.writeCollectionOfObjectValues<DeviceManagementPartner>("deviceManagementPartners", deviceManagement.deviceManagementPartners, serializeDeviceManagementPartner);
        writer.writeCollectionOfObjectValues<DeviceManagementExchangeConnector>("exchangeConnectors", deviceManagement.exchangeConnectors, serializeDeviceManagementExchangeConnector);
        writer.writeCollectionOfObjectValues<ImportedWindowsAutopilotDeviceIdentity>("importedWindowsAutopilotDeviceIdentities", deviceManagement.importedWindowsAutopilotDeviceIdentities, serializeImportedWindowsAutopilotDeviceIdentity);
        writer.writeStringValue("intuneAccountId", deviceManagement.intuneAccountId);
        writer.writeObjectValue<IntuneBrand>("intuneBrand", deviceManagement.intuneBrand, serializeIntuneBrand);
        writer.writeCollectionOfObjectValues<IosUpdateDeviceStatus>("iosUpdateStatuses", deviceManagement.iosUpdateStatuses, serializeIosUpdateDeviceStatus);
        writer.writeObjectValue<ManagedDeviceOverview>("managedDeviceOverview", deviceManagement.managedDeviceOverview, serializeManagedDeviceOverview);
        writer.writeCollectionOfObjectValues<ManagedDevice>("managedDevices", deviceManagement.managedDevices, serializeManagedDevice);
        writer.writeCollectionOfObjectValues<MobileThreatDefenseConnector>("mobileThreatDefenseConnectors", deviceManagement.mobileThreatDefenseConnectors, serializeMobileThreatDefenseConnector);
        writer.writeCollectionOfObjectValues<NotificationMessageTemplate>("notificationMessageTemplates", deviceManagement.notificationMessageTemplates, serializeNotificationMessageTemplate);
        writer.writeCollectionOfObjectValues<RemoteAssistancePartner>("remoteAssistancePartners", deviceManagement.remoteAssistancePartners, serializeRemoteAssistancePartner);
        writer.writeObjectValue<DeviceManagementReports>("reports", deviceManagement.reports, serializeDeviceManagementReports);
        writer.writeCollectionOfObjectValues<ResourceOperation>("resourceOperations", deviceManagement.resourceOperations, serializeResourceOperation);
        writer.writeCollectionOfObjectValues<DeviceAndAppManagementRoleAssignment>("roleAssignments", deviceManagement.roleAssignments, serializeDeviceAndAppManagementRoleAssignment);
        writer.writeCollectionOfObjectValues<RoleDefinition>("roleDefinitions", deviceManagement.roleDefinitions, serializeRoleDefinition);
        writer.writeObjectValue<DeviceManagementSettings>("settings", deviceManagement.settings, serializeDeviceManagementSettings);
        writer.writeObjectValue<SoftwareUpdateStatusSummary>("softwareUpdateStatusSummary", deviceManagement.softwareUpdateStatusSummary, serializeSoftwareUpdateStatusSummary);
        writer.writeEnumValue<DeviceManagementSubscriptionState>("subscriptionState", deviceManagement.subscriptionState);
        writer.writeCollectionOfObjectValues<TelecomExpenseManagementPartner>("telecomExpenseManagementPartners", deviceManagement.telecomExpenseManagementPartners, serializeTelecomExpenseManagementPartner);
        writer.writeCollectionOfObjectValues<TermsAndConditions>("termsAndConditions", deviceManagement.termsAndConditions, serializeTermsAndConditions);
        writer.writeCollectionOfObjectValues<DeviceManagementTroubleshootingEvent>("troubleshootingEvents", deviceManagement.troubleshootingEvents, serializeDeviceManagementTroubleshootingEvent);
        writer.writeCollectionOfObjectValues<WindowsAutopilotDeviceIdentity>("windowsAutopilotDeviceIdentities", deviceManagement.windowsAutopilotDeviceIdentities, serializeWindowsAutopilotDeviceIdentity);
        writer.writeCollectionOfObjectValues<WindowsInformationProtectionAppLearningSummary>("windowsInformationProtectionAppLearningSummaries", deviceManagement.windowsInformationProtectionAppLearningSummaries, serializeWindowsInformationProtectionAppLearningSummary);
        writer.writeCollectionOfObjectValues<WindowsInformationProtectionNetworkLearningSummary>("windowsInformationProtectionNetworkLearningSummaries", deviceManagement.windowsInformationProtectionNetworkLearningSummaries, serializeWindowsInformationProtectionNetworkLearningSummary);
}
