import {AccessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource} from './accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource';
import {serializeAccessReviewInstanceDecisionItemResource} from './serializeAccessReviewInstanceDecisionItemResource';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeAccessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource(accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource: AccessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource | undefined = {} as AccessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource, writer: SerializationWriter) : void {
        serializeAccessReviewInstanceDecisionItemResource(writer, accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource)
        writer.writeStringValue("accessPackageDisplayName", accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource.accessPackageDisplayName);
        writer.writeStringValue("accessPackageId", accessReviewInstanceDecisionItemAccessPackageAssignmentPolicyResource.accessPackageId);
}
