import {AndroidGeneralDeviceConfiguration} from './androidGeneralDeviceConfiguration';
import {AndroidRequiredPasswordType} from './androidRequiredPasswordType';
import {AppListItem} from './appListItem';
import {AppListType} from './appListType';
import {serializeAppListItem} from './serializeAppListItem';
import {serializeDeviceConfiguration} from './serializeDeviceConfiguration';
import {WebBrowserCookieSettings} from './webBrowserCookieSettings';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeAndroidGeneralDeviceConfiguration(writer: SerializationWriter, androidGeneralDeviceConfiguration: AndroidGeneralDeviceConfiguration | undefined = {} as AndroidGeneralDeviceConfiguration) : void {
        serializeDeviceConfiguration(writer, androidGeneralDeviceConfiguration)
        writer.writeBooleanValue("appsBlockClipboardSharing", androidGeneralDeviceConfiguration.appsBlockClipboardSharing);
        writer.writeBooleanValue("appsBlockCopyPaste", androidGeneralDeviceConfiguration.appsBlockCopyPaste);
        writer.writeBooleanValue("appsBlockYouTube", androidGeneralDeviceConfiguration.appsBlockYouTube);
        writer.writeCollectionOfObjectValues<AppListItem>("appsHideList", androidGeneralDeviceConfiguration.appsHideList, serializeAppListItem);
        writer.writeCollectionOfObjectValues<AppListItem>("appsInstallAllowList", androidGeneralDeviceConfiguration.appsInstallAllowList, serializeAppListItem);
        writer.writeCollectionOfObjectValues<AppListItem>("appsLaunchBlockList", androidGeneralDeviceConfiguration.appsLaunchBlockList, serializeAppListItem);
        writer.writeBooleanValue("bluetoothBlocked", androidGeneralDeviceConfiguration.bluetoothBlocked);
        writer.writeBooleanValue("cameraBlocked", androidGeneralDeviceConfiguration.cameraBlocked);
        writer.writeBooleanValue("cellularBlockDataRoaming", androidGeneralDeviceConfiguration.cellularBlockDataRoaming);
        writer.writeBooleanValue("cellularBlockMessaging", androidGeneralDeviceConfiguration.cellularBlockMessaging);
        writer.writeBooleanValue("cellularBlockVoiceRoaming", androidGeneralDeviceConfiguration.cellularBlockVoiceRoaming);
        writer.writeBooleanValue("cellularBlockWiFiTethering", androidGeneralDeviceConfiguration.cellularBlockWiFiTethering);
        writer.writeEnumValue<AppListType>("compliantAppListType", androidGeneralDeviceConfiguration.compliantAppListType);
        writer.writeCollectionOfObjectValues<AppListItem>("compliantAppsList", androidGeneralDeviceConfiguration.compliantAppsList, serializeAppListItem);
        writer.writeBooleanValue("deviceSharingAllowed", androidGeneralDeviceConfiguration.deviceSharingAllowed);
        writer.writeBooleanValue("diagnosticDataBlockSubmission", androidGeneralDeviceConfiguration.diagnosticDataBlockSubmission);
        writer.writeBooleanValue("factoryResetBlocked", androidGeneralDeviceConfiguration.factoryResetBlocked);
        writer.writeBooleanValue("googleAccountBlockAutoSync", androidGeneralDeviceConfiguration.googleAccountBlockAutoSync);
        writer.writeBooleanValue("googlePlayStoreBlocked", androidGeneralDeviceConfiguration.googlePlayStoreBlocked);
        writer.writeCollectionOfObjectValues<AppListItem>("kioskModeApps", androidGeneralDeviceConfiguration.kioskModeApps, serializeAppListItem);
        writer.writeBooleanValue("kioskModeBlockSleepButton", androidGeneralDeviceConfiguration.kioskModeBlockSleepButton);
        writer.writeBooleanValue("kioskModeBlockVolumeButtons", androidGeneralDeviceConfiguration.kioskModeBlockVolumeButtons);
        writer.writeBooleanValue("locationServicesBlocked", androidGeneralDeviceConfiguration.locationServicesBlocked);
        writer.writeBooleanValue("nfcBlocked", androidGeneralDeviceConfiguration.nfcBlocked);
        writer.writeBooleanValue("passwordBlockFingerprintUnlock", androidGeneralDeviceConfiguration.passwordBlockFingerprintUnlock);
        writer.writeBooleanValue("passwordBlockTrustAgents", androidGeneralDeviceConfiguration.passwordBlockTrustAgents);
        writer.writeNumberValue("passwordExpirationDays", androidGeneralDeviceConfiguration.passwordExpirationDays);
        writer.writeNumberValue("passwordMinimumLength", androidGeneralDeviceConfiguration.passwordMinimumLength);
        writer.writeNumberValue("passwordMinutesOfInactivityBeforeScreenTimeout", androidGeneralDeviceConfiguration.passwordMinutesOfInactivityBeforeScreenTimeout);
        writer.writeNumberValue("passwordPreviousPasswordBlockCount", androidGeneralDeviceConfiguration.passwordPreviousPasswordBlockCount);
        writer.writeBooleanValue("passwordRequired", androidGeneralDeviceConfiguration.passwordRequired);
        writer.writeEnumValue<AndroidRequiredPasswordType>("passwordRequiredType", androidGeneralDeviceConfiguration.passwordRequiredType);
        writer.writeNumberValue("passwordSignInFailureCountBeforeFactoryReset", androidGeneralDeviceConfiguration.passwordSignInFailureCountBeforeFactoryReset);
        writer.writeBooleanValue("powerOffBlocked", androidGeneralDeviceConfiguration.powerOffBlocked);
        writer.writeBooleanValue("screenCaptureBlocked", androidGeneralDeviceConfiguration.screenCaptureBlocked);
        writer.writeBooleanValue("securityRequireVerifyApps", androidGeneralDeviceConfiguration.securityRequireVerifyApps);
        writer.writeBooleanValue("storageBlockGoogleBackup", androidGeneralDeviceConfiguration.storageBlockGoogleBackup);
        writer.writeBooleanValue("storageBlockRemovableStorage", androidGeneralDeviceConfiguration.storageBlockRemovableStorage);
        writer.writeBooleanValue("storageRequireDeviceEncryption", androidGeneralDeviceConfiguration.storageRequireDeviceEncryption);
        writer.writeBooleanValue("storageRequireRemovableStorageEncryption", androidGeneralDeviceConfiguration.storageRequireRemovableStorageEncryption);
        writer.writeBooleanValue("voiceAssistantBlocked", androidGeneralDeviceConfiguration.voiceAssistantBlocked);
        writer.writeBooleanValue("voiceDialingBlocked", androidGeneralDeviceConfiguration.voiceDialingBlocked);
        writer.writeBooleanValue("webBrowserBlockAutofill", androidGeneralDeviceConfiguration.webBrowserBlockAutofill);
        writer.writeBooleanValue("webBrowserBlocked", androidGeneralDeviceConfiguration.webBrowserBlocked);
        writer.writeBooleanValue("webBrowserBlockJavaScript", androidGeneralDeviceConfiguration.webBrowserBlockJavaScript);
        writer.writeBooleanValue("webBrowserBlockPopups", androidGeneralDeviceConfiguration.webBrowserBlockPopups);
        writer.writeEnumValue<WebBrowserCookieSettings>("webBrowserCookieSettings", androidGeneralDeviceConfiguration.webBrowserCookieSettings);
        writer.writeBooleanValue("wiFiBlocked", androidGeneralDeviceConfiguration.wiFiBlocked);
}
