import { type Audio } from './audio';
import { type Bundle } from './bundle';
import { type Deleted } from './deleted';
import { type DriveItem } from './driveItem';
import { type DriveItemVersion } from './driveItemVersion';
import { type File } from './file';
import { type FileSystemInfo } from './fileSystemInfo';
import { type Folder } from './folder';
import { type GeoCoordinates } from './geoCoordinates';
import { type Image } from './image';
import { type ItemAnalytics } from './itemAnalytics';
import { type ListItem } from './listItem';
import { type Malware } from './malware';
import { type PackageEscaped } from './packageEscaped';
import { type PendingOperations } from './pendingOperations';
import { type Permission } from './permission';
import { type Photo } from './photo';
import { type PublicationFacet } from './publicationFacet';
import { type RemoteItem } from './remoteItem';
import { type Root } from './root';
import { type SearchResult } from './searchResult';
import { serializeAudio } from './serializeAudio';
import { serializeBaseItem } from './serializeBaseItem';
import { serializeBundle } from './serializeBundle';
import { serializeDeleted } from './serializeDeleted';
import { serializeDriveItemVersion } from './serializeDriveItemVersion';
import { serializeFile } from './serializeFile';
import { serializeFileSystemInfo } from './serializeFileSystemInfo';
import { serializeFolder } from './serializeFolder';
import { serializeGeoCoordinates } from './serializeGeoCoordinates';
import { serializeImage } from './serializeImage';
import { serializeItemAnalytics } from './serializeItemAnalytics';
import { serializeListItem } from './serializeListItem';
import { serializeMalware } from './serializeMalware';
import { serializePackageEscaped } from './serializePackageEscaped';
import { serializePendingOperations } from './serializePendingOperations';
import { serializePermission } from './serializePermission';
import { serializePhoto } from './serializePhoto';
import { serializePublicationFacet } from './serializePublicationFacet';
import { serializeRemoteItem } from './serializeRemoteItem';
import { serializeRoot } from './serializeRoot';
import { serializeSearchResult } from './serializeSearchResult';
import { serializeShared } from './serializeShared';
import { serializeSharepointIds } from './serializeSharepointIds';
import { serializeSpecialFolder } from './serializeSpecialFolder';
import { serializeSubscription } from './serializeSubscription';
import { serializeThumbnailSet } from './serializeThumbnailSet';
import { serializeVideo } from './serializeVideo';
import { serializeWorkbook } from './serializeWorkbook';
import { type Shared } from './shared';
import { type SharepointIds } from './sharepointIds';
import { type SpecialFolder } from './specialFolder';
import { type Subscription } from './subscription';
import { type ThumbnailSet } from './thumbnailSet';
import { type Video } from './video';
import { type Workbook } from './workbook';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function serializeDriveItem(writer: SerializationWriter, driveItem: DriveItem | undefined = {} as DriveItem) : void {
        serializeBaseItem(writer, driveItem)
        writer.writeObjectValue<ItemAnalytics>("analytics", driveItem.analytics, serializeItemAnalytics);
        writer.writeObjectValue<Audio>("audio", driveItem.audio, serializeAudio);
        writer.writeObjectValue<Bundle>("bundle", driveItem.bundle, serializeBundle);
        writer.writeCollectionOfObjectValues<DriveItem>("children", driveItem.children, serializeDriveItem);
        writer.writeStringValue("content", driveItem.content);
        writer.writeStringValue("cTag", driveItem.cTag);
        writer.writeObjectValue<Deleted>("deleted", driveItem.deleted, serializeDeleted);
        writer.writeObjectValue<File>("file", driveItem.file, serializeFile);
        writer.writeObjectValue<FileSystemInfo>("fileSystemInfo", driveItem.fileSystemInfo, serializeFileSystemInfo);
        writer.writeObjectValue<Folder>("folder", driveItem.folder, serializeFolder);
        writer.writeObjectValue<Image>("image", driveItem.image, serializeImage);
        writer.writeObjectValue<ListItem>("listItem", driveItem.listItem, serializeListItem);
        writer.writeObjectValue<GeoCoordinates>("location", driveItem.location, serializeGeoCoordinates);
        writer.writeObjectValue<Malware>("malware", driveItem.malware, serializeMalware);
        writer.writeObjectValue<PackageEscaped>("package", driveItem.packageEscaped, serializePackageEscaped);
        writer.writeObjectValue<PendingOperations>("pendingOperations", driveItem.pendingOperations, serializePendingOperations);
        writer.writeCollectionOfObjectValues<Permission>("permissions", driveItem.permissions, serializePermission);
        writer.writeObjectValue<Photo>("photo", driveItem.photo, serializePhoto);
        writer.writeObjectValue<PublicationFacet>("publication", driveItem.publication, serializePublicationFacet);
        writer.writeObjectValue<RemoteItem>("remoteItem", driveItem.remoteItem, serializeRemoteItem);
        writer.writeObjectValue<Root>("root", driveItem.root, serializeRoot);
        writer.writeObjectValue<SearchResult>("searchResult", driveItem.searchResult, serializeSearchResult);
        writer.writeObjectValue<Shared>("shared", driveItem.shared, serializeShared);
        writer.writeObjectValue<SharepointIds>("sharepointIds", driveItem.sharepointIds, serializeSharepointIds);
        writer.writeNumberValue("size", driveItem.size);
        writer.writeObjectValue<SpecialFolder>("specialFolder", driveItem.specialFolder, serializeSpecialFolder);
        writer.writeCollectionOfObjectValues<Subscription>("subscriptions", driveItem.subscriptions, serializeSubscription);
        writer.writeCollectionOfObjectValues<ThumbnailSet>("thumbnails", driveItem.thumbnails, serializeThumbnailSet);
        writer.writeCollectionOfObjectValues<DriveItemVersion>("versions", driveItem.versions, serializeDriveItemVersion);
        writer.writeObjectValue<Video>("video", driveItem.video, serializeVideo);
        writer.writeStringValue("webDavUrl", driveItem.webDavUrl);
        writer.writeObjectValue<Workbook>("workbook", driveItem.workbook, serializeWorkbook);
}
