import {serializeBaseCollectionPaginationCountResponse} from './serializeBaseCollectionPaginationCountResponse';
import {serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails} from './serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import {UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails} from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails';
import {UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse} from './userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse(writer: SerializationWriter, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse: UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse | undefined = {} as UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse) : void {
        serializeBaseCollectionPaginationCountResponse(writer, userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse)
        writer.writeCollectionOfObjectValues<UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails>("value", userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsCollectionResponse.value, serializeUserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails);
}
