import type {Alert} from './alert';
import type {AlertDetection} from './alertDetection';
import {AlertFeedback} from './alertFeedback';
import type {AlertHistoryState} from './alertHistoryState';
import {AlertSeverity} from './alertSeverity';
import {AlertStatus} from './alertStatus';
import type {AlertTrigger} from './alertTrigger';
import type {CloudAppSecurityState} from './cloudAppSecurityState';
import type {FileSecurityState} from './fileSecurityState';
import type {HostSecurityState} from './hostSecurityState';
import type {InvestigationSecurityState} from './investigationSecurityState';
import type {MalwareState} from './malwareState';
import type {MessageSecurityState} from './messageSecurityState';
import type {NetworkConnection} from './networkConnection';
import type {Process} from './process';
import type {RegistryKeyState} from './registryKeyState';
import type {SecurityResource} from './securityResource';
import type {SecurityVendorInformation} from './securityVendorInformation';
import {serializeAlertDetection} from './serializeAlertDetection';
import {serializeAlertHistoryState} from './serializeAlertHistoryState';
import {serializeAlertTrigger} from './serializeAlertTrigger';
import {serializeCloudAppSecurityState} from './serializeCloudAppSecurityState';
import {serializeEntity} from './serializeEntity';
import {serializeFileSecurityState} from './serializeFileSecurityState';
import {serializeHostSecurityState} from './serializeHostSecurityState';
import {serializeInvestigationSecurityState} from './serializeInvestigationSecurityState';
import {serializeMalwareState} from './serializeMalwareState';
import {serializeMessageSecurityState} from './serializeMessageSecurityState';
import {serializeNetworkConnection} from './serializeNetworkConnection';
import {serializeProcess} from './serializeProcess';
import {serializeRegistryKeyState} from './serializeRegistryKeyState';
import {serializeSecurityResource} from './serializeSecurityResource';
import {serializeSecurityVendorInformation} from './serializeSecurityVendorInformation';
import {serializeUriClickSecurityState} from './serializeUriClickSecurityState';
import {serializeUserSecurityState} from './serializeUserSecurityState';
import {serializeVulnerabilityState} from './serializeVulnerabilityState';
import type {UriClickSecurityState} from './uriClickSecurityState';
import type {UserSecurityState} from './userSecurityState';
import type {VulnerabilityState} from './vulnerabilityState';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeAlert(writer: SerializationWriter, alert: Alert | undefined = {} as Alert) : void {
        serializeEntity(writer, alert)
        writer.writeStringValue("activityGroupName", alert.activityGroupName);
        writer.writeCollectionOfObjectValues<AlertDetection>("alertDetections", alert.alertDetections, serializeAlertDetection);
        writer.writeStringValue("assignedTo", alert.assignedTo);
        writer.writeStringValue("azureSubscriptionId", alert.azureSubscriptionId);
        writer.writeStringValue("azureTenantId", alert.azureTenantId);
        writer.writeStringValue("category", alert.category);
        writer.writeDateValue("closedDateTime", alert.closedDateTime);
        writer.writeCollectionOfObjectValues<CloudAppSecurityState>("cloudAppStates", alert.cloudAppStates, serializeCloudAppSecurityState);
        writer.writeCollectionOfPrimitiveValues<string>("comments", alert.comments);
        writer.writeNumberValue("confidence", alert.confidence);
        writer.writeDateValue("createdDateTime", alert.createdDateTime);
        writer.writeStringValue("description", alert.description);
        writer.writeCollectionOfPrimitiveValues<string>("detectionIds", alert.detectionIds);
        writer.writeDateValue("eventDateTime", alert.eventDateTime);
        writer.writeEnumValue<AlertFeedback>("feedback", alert.feedback);
        writer.writeCollectionOfObjectValues<FileSecurityState>("fileStates", alert.fileStates, serializeFileSecurityState);
        writer.writeCollectionOfObjectValues<AlertHistoryState>("historyStates", alert.historyStates, serializeAlertHistoryState);
        writer.writeCollectionOfObjectValues<HostSecurityState>("hostStates", alert.hostStates, serializeHostSecurityState);
        writer.writeCollectionOfPrimitiveValues<string>("incidentIds", alert.incidentIds);
        writer.writeCollectionOfObjectValues<InvestigationSecurityState>("investigationSecurityStates", alert.investigationSecurityStates, serializeInvestigationSecurityState);
        writer.writeDateValue("lastEventDateTime", alert.lastEventDateTime);
        writer.writeDateValue("lastModifiedDateTime", alert.lastModifiedDateTime);
        writer.writeCollectionOfObjectValues<MalwareState>("malwareStates", alert.malwareStates, serializeMalwareState);
        writer.writeCollectionOfObjectValues<MessageSecurityState>("messageSecurityStates", alert.messageSecurityStates, serializeMessageSecurityState);
        writer.writeCollectionOfObjectValues<NetworkConnection>("networkConnections", alert.networkConnections, serializeNetworkConnection);
        writer.writeCollectionOfObjectValues<Process>("processes", alert.processes, serializeProcess);
        writer.writeCollectionOfPrimitiveValues<string>("recommendedActions", alert.recommendedActions);
        writer.writeCollectionOfObjectValues<RegistryKeyState>("registryKeyStates", alert.registryKeyStates, serializeRegistryKeyState);
        writer.writeCollectionOfObjectValues<SecurityResource>("securityResources", alert.securityResources, serializeSecurityResource);
        writer.writeEnumValue<AlertSeverity>("severity", alert.severity);
        writer.writeCollectionOfPrimitiveValues<string>("sourceMaterials", alert.sourceMaterials);
        writer.writeEnumValue<AlertStatus>("status", alert.status);
        writer.writeCollectionOfPrimitiveValues<string>("tags", alert.tags);
        writer.writeStringValue("title", alert.title);
        writer.writeCollectionOfObjectValues<AlertTrigger>("triggers", alert.triggers, serializeAlertTrigger);
        writer.writeCollectionOfObjectValues<UriClickSecurityState>("uriClickSecurityStates", alert.uriClickSecurityStates, serializeUriClickSecurityState);
        writer.writeCollectionOfObjectValues<UserSecurityState>("userStates", alert.userStates, serializeUserSecurityState);
        writer.writeObjectValue<SecurityVendorInformation>("vendorInformation", alert.vendorInformation, serializeSecurityVendorInformation);
        writer.writeCollectionOfObjectValues<VulnerabilityState>("vulnerabilityStates", alert.vulnerabilityStates, serializeVulnerabilityState);
}
