// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoEntity, serializeEntity, type Entity } from './entity';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createTeamsTemplateFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoTeamsTemplate;
}
export function deserializeIntoTeamsTemplate(teamsTemplate: TeamsTemplate | undefined = {} as TeamsTemplate) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoEntity(teamsTemplate),
    }
}
export function serializeTeamsTemplate(writer: SerializationWriter, teamsTemplate: TeamsTemplate | undefined = {} as TeamsTemplate) : void {
        serializeEntity(writer, teamsTemplate)
}
export interface TeamsTemplate extends Entity, Parsable {
}
// tslint:enable
// eslint-enable
