import { createAppScopeFromDiscriminatorValue, serializeAppScope, type AppScope } from './appScope';
import { createDirectoryObjectFromDiscriminatorValue, serializeDirectoryObject, type DirectoryObject } from './directoryObject';
import { deserializeIntoEntity, serializeEntity, type Entity } from './entity';
import { type UnifiedRoleAssignmentSchedule, type UnifiedRoleEligibilitySchedule } from './index';
import { deserializeIntoUnifiedRoleAssignmentSchedule } from './unifiedRoleAssignmentSchedule';
import { createUnifiedRoleDefinitionFromDiscriminatorValue, serializeUnifiedRoleDefinition, type UnifiedRoleDefinition } from './unifiedRoleDefinition';
import { deserializeIntoUnifiedRoleEligibilitySchedule } from './unifiedRoleEligibilitySchedule';
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function createUnifiedRoleScheduleBaseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    const mappingValueNode = parseNode.getChildNode("@odata.type");
    if (mappingValueNode) {
        const mappingValue = mappingValueNode.getStringValue();
        if (mappingValue) {
            switch (mappingValue) {
                case "#microsoft.graph.unifiedRoleAssignmentSchedule":
                    return deserializeIntoUnifiedRoleAssignmentSchedule;
                case "#microsoft.graph.unifiedRoleEligibilitySchedule":
                    return deserializeIntoUnifiedRoleEligibilitySchedule;
            }
        }
    }
    return deserializeIntoUnifiedRoleScheduleBase;
}
// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function deserializeIntoUnifiedRoleScheduleBase(unifiedRoleScheduleBase: UnifiedRoleScheduleBase | undefined = {} as UnifiedRoleScheduleBase) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoEntity(unifiedRoleScheduleBase),
        "appScope": n => { unifiedRoleScheduleBase.appScope = n.getObjectValue<AppScope>(createAppScopeFromDiscriminatorValue); },
        "appScopeId": n => { unifiedRoleScheduleBase.appScopeId = n.getStringValue(); },
        "createdDateTime": n => { unifiedRoleScheduleBase.createdDateTime = n.getDateValue(); },
        "createdUsing": n => { unifiedRoleScheduleBase.createdUsing = n.getStringValue(); },
        "directoryScope": n => { unifiedRoleScheduleBase.directoryScope = n.getObjectValue<DirectoryObject>(createDirectoryObjectFromDiscriminatorValue); },
        "directoryScopeId": n => { unifiedRoleScheduleBase.directoryScopeId = n.getStringValue(); },
        "modifiedDateTime": n => { unifiedRoleScheduleBase.modifiedDateTime = n.getDateValue(); },
        "principal": n => { unifiedRoleScheduleBase.principal = n.getObjectValue<DirectoryObject>(createDirectoryObjectFromDiscriminatorValue); },
        "principalId": n => { unifiedRoleScheduleBase.principalId = n.getStringValue(); },
        "roleDefinition": n => { unifiedRoleScheduleBase.roleDefinition = n.getObjectValue<UnifiedRoleDefinition>(createUnifiedRoleDefinitionFromDiscriminatorValue); },
        "roleDefinitionId": n => { unifiedRoleScheduleBase.roleDefinitionId = n.getStringValue(); },
        "status": n => { unifiedRoleScheduleBase.status = n.getStringValue(); },
    }
}
// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
export function serializeUnifiedRoleScheduleBase(writer: SerializationWriter, unifiedRoleScheduleBase: UnifiedRoleScheduleBase | undefined = {} as UnifiedRoleScheduleBase) : void {
        serializeEntity(writer, unifiedRoleScheduleBase)
        writer.writeObjectValue<AppScope>("appScope", unifiedRoleScheduleBase.appScope, );
        writer.writeStringValue("appScopeId", unifiedRoleScheduleBase.appScopeId);
        writer.writeDateValue("createdDateTime", unifiedRoleScheduleBase.createdDateTime);
        writer.writeStringValue("createdUsing", unifiedRoleScheduleBase.createdUsing);
        writer.writeObjectValue<DirectoryObject>("directoryScope", unifiedRoleScheduleBase.directoryScope, );
        writer.writeStringValue("directoryScopeId", unifiedRoleScheduleBase.directoryScopeId);
        writer.writeDateValue("modifiedDateTime", unifiedRoleScheduleBase.modifiedDateTime);
        writer.writeObjectValue<DirectoryObject>("principal", unifiedRoleScheduleBase.principal, );
        writer.writeStringValue("principalId", unifiedRoleScheduleBase.principalId);
        writer.writeObjectValue<UnifiedRoleDefinition>("roleDefinition", unifiedRoleScheduleBase.roleDefinition, );
        writer.writeStringValue("roleDefinitionId", unifiedRoleScheduleBase.roleDefinitionId);
        writer.writeStringValue("status", unifiedRoleScheduleBase.status);
}
export interface UnifiedRoleScheduleBase extends Entity, Parsable {
    /**
     * Read-only property with details of the app-specific scope when the role eligibility or assignment is scoped to an app. Nullable.
     */
    appScope?: AppScope;
    /**
     * Identifier of the app-specific scope when the assignment or eligibility is scoped to an app. The scope of an assignment or eligibility determines the set of resources for which the principal has been granted access. App scopes are scopes that are defined and understood by this application only. Use / for tenant-wide app scopes. Use directoryScopeId to limit the scope to particular directory objects, for example, administrative units.
     */
    appScopeId?: string;
    /**
     * When the schedule was created.
     */
    createdDateTime?: Date;
    /**
     * Identifier of the object through which this schedule was created.
     */
    createdUsing?: string;
    /**
     * The directory object that is the scope of the role eligibility or assignment. Read-only.
     */
    directoryScope?: DirectoryObject;
    /**
     * Identifier of the directory object representing the scope of the assignment or eligibility. The scope of an assignment or eligibility determines the set of resources for which the principal has been granted access. Directory scopes are shared scopes stored in the directory that are understood by multiple applications. Use / for tenant-wide scope. Use appScopeId to limit the scope to an application only.
     */
    directoryScopeId?: string;
    /**
     * When the schedule was last modified.
     */
    modifiedDateTime?: Date;
    /**
     * The principal that's getting a role assignment or that's eligible for a role through the request.
     */
    principal?: DirectoryObject;
    /**
     * Identifier of the principal that has been granted the role assignment or eligibility.
     */
    principalId?: string;
    /**
     * Detailed information for the roleDefinition object that is referenced through the roleDefinitionId property.
     */
    roleDefinition?: UnifiedRoleDefinition;
    /**
     * Identifier of the unifiedRoleDefinition object that is being assigned to the principal or that a principal is eligible for.
     */
    roleDefinitionId?: string;
    /**
     * The status of the role assignment or eligibility request.
     */
    status?: string;
}
