export * from './telecomExpenseManagementPartnerItemRequestBuilderDeleteRequestConfiguration'
export * from './telecomExpenseManagementPartnerItemRequestBuilderGetQueryParameters'
export * from './telecomExpenseManagementPartnerItemRequestBuilderGetRequestConfiguration'
export * from './telecomExpenseManagementPartnerItemRequestBuilderPatchRequestConfiguration'
